// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: resource.proto

package resourcerpc

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/blog-gozero/service/rpc/blog/internal/pb/resourcerpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlbumDetailsResp     = resourcerpc.AlbumDetailsResp
	BatchResp            = resourcerpc.BatchResp
	EmptyResp            = resourcerpc.EmptyResp
	FindAlbumListReq     = resourcerpc.FindAlbumListReq
	FindAlbumListResp    = resourcerpc.FindAlbumListResp
	FindPageListReq      = resourcerpc.FindPageListReq
	FindPageListResp     = resourcerpc.FindPageListResp
	FindPhotoListReq     = resourcerpc.FindPhotoListReq
	FindPhotoListResp    = resourcerpc.FindPhotoListResp
	IdReq                = resourcerpc.IdReq
	IdsReq               = resourcerpc.IdsReq
	NewAlbumReq          = resourcerpc.NewAlbumReq
	NewPageReq           = resourcerpc.NewPageReq
	NewPhotoReq          = resourcerpc.NewPhotoReq
	PageDetailsResp      = resourcerpc.PageDetailsResp
	PageReq              = resourcerpc.PageReq
	PageResp             = resourcerpc.PageResp
	PhotoDetailsResp     = resourcerpc.PhotoDetailsResp
	UpdateAlbumDeleteReq = resourcerpc.UpdateAlbumDeleteReq
	UpdatePhotoDeleteReq = resourcerpc.UpdatePhotoDeleteReq

	ResourceRpc interface {
		// 创建照片
		AddPhoto(ctx context.Context, in *NewPhotoReq, opts ...grpc.CallOption) (*PhotoDetailsResp, error)
		// 更新照片
		UpdatePhoto(ctx context.Context, in *NewPhotoReq, opts ...grpc.CallOption) (*PhotoDetailsResp, error)
		// 更新照片删除状态
		UpdatePhotoDelete(ctx context.Context, in *UpdatePhotoDeleteReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 删除照片
		DeletesPhoto(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询照片列表
		FindPhotoList(ctx context.Context, in *FindPhotoListReq, opts ...grpc.CallOption) (*FindPhotoListResp, error)
		// 创建相册
		AddAlbum(ctx context.Context, in *NewAlbumReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error)
		// 更新相册
		UpdateAlbum(ctx context.Context, in *NewAlbumReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error)
		// 更新相册删除状态
		UpdateAlbumDelete(ctx context.Context, in *UpdateAlbumDeleteReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 获取相册
		GetAlbum(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error)
		// 删除相册
		DeletesAlbum(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询相册列表
		FindAlbumList(ctx context.Context, in *FindAlbumListReq, opts ...grpc.CallOption) (*FindAlbumListResp, error)
		// 创建页面
		AddPage(ctx context.Context, in *NewPageReq, opts ...grpc.CallOption) (*PageDetailsResp, error)
		// 更新页面
		UpdatePage(ctx context.Context, in *NewPageReq, opts ...grpc.CallOption) (*PageDetailsResp, error)
		// 删除页面
		DeletesPage(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询页面列表
		FindPageList(ctx context.Context, in *FindPageListReq, opts ...grpc.CallOption) (*FindPageListResp, error)
	}

	defaultResourceRpc struct {
		cli zrpc.Client
	}
)

func NewResourceRpc(cli zrpc.Client) ResourceRpc {
	return &defaultResourceRpc{
		cli: cli,
	}
}

// 创建照片
func (m *defaultResourceRpc) AddPhoto(ctx context.Context, in *NewPhotoReq, opts ...grpc.CallOption) (*PhotoDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.AddPhoto(ctx, in, opts...)
}

// 更新照片
func (m *defaultResourceRpc) UpdatePhoto(ctx context.Context, in *NewPhotoReq, opts ...grpc.CallOption) (*PhotoDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.UpdatePhoto(ctx, in, opts...)
}

// 更新照片删除状态
func (m *defaultResourceRpc) UpdatePhotoDelete(ctx context.Context, in *UpdatePhotoDeleteReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.UpdatePhotoDelete(ctx, in, opts...)
}

// 删除照片
func (m *defaultResourceRpc) DeletesPhoto(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.DeletesPhoto(ctx, in, opts...)
}

// 查询照片列表
func (m *defaultResourceRpc) FindPhotoList(ctx context.Context, in *FindPhotoListReq, opts ...grpc.CallOption) (*FindPhotoListResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.FindPhotoList(ctx, in, opts...)
}

// 创建相册
func (m *defaultResourceRpc) AddAlbum(ctx context.Context, in *NewAlbumReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.AddAlbum(ctx, in, opts...)
}

// 更新相册
func (m *defaultResourceRpc) UpdateAlbum(ctx context.Context, in *NewAlbumReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.UpdateAlbum(ctx, in, opts...)
}

// 更新相册删除状态
func (m *defaultResourceRpc) UpdateAlbumDelete(ctx context.Context, in *UpdateAlbumDeleteReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.UpdateAlbumDelete(ctx, in, opts...)
}

// 获取相册
func (m *defaultResourceRpc) GetAlbum(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AlbumDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.GetAlbum(ctx, in, opts...)
}

// 删除相册
func (m *defaultResourceRpc) DeletesAlbum(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.DeletesAlbum(ctx, in, opts...)
}

// 查询相册列表
func (m *defaultResourceRpc) FindAlbumList(ctx context.Context, in *FindAlbumListReq, opts ...grpc.CallOption) (*FindAlbumListResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.FindAlbumList(ctx, in, opts...)
}

// 创建页面
func (m *defaultResourceRpc) AddPage(ctx context.Context, in *NewPageReq, opts ...grpc.CallOption) (*PageDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.AddPage(ctx, in, opts...)
}

// 更新页面
func (m *defaultResourceRpc) UpdatePage(ctx context.Context, in *NewPageReq, opts ...grpc.CallOption) (*PageDetailsResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.UpdatePage(ctx, in, opts...)
}

// 删除页面
func (m *defaultResourceRpc) DeletesPage(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.DeletesPage(ctx, in, opts...)
}

// 查询页面列表
func (m *defaultResourceRpc) FindPageList(ctx context.Context, in *FindPageListReq, opts ...grpc.CallOption) (*FindPageListResp, error) {
	client := resourcerpc.NewResourceRpcClient(m.cli.Conn())
	return client.FindPageList(ctx, in, opts...)
}
