apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
    - name: peer
      port: 2380
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: rancher/etcd:v3.4.13
          command:
            - etcd
            - --name=etcd
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://etcd:2380
            - --initial-cluster=etcd=http://etcd:2380
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - name: data
              mountPath: /var/lib/etcd
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: etcd-pvc
