// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: website.proto

// proto 包名

package websiterpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebsiteRpc_AnalysisVisit_FullMethodName  = "/websiterpc.WebsiteRpc/AnalysisVisit"
	WebsiteRpc_AddVisit_FullMethodName       = "/websiterpc.WebsiteRpc/AddVisit"
	WebsiteRpc_FindVisitTrend_FullMethodName = "/websiterpc.WebsiteRpc/FindVisitTrend"
)

// WebsiteRpcClient is the client API for WebsiteRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebsiteRpcClient interface {
	// 用户日浏览量分析
	AnalysisVisit(ctx context.Context, in *AnalysisVisitReq, opts ...grpc.CallOption) (*AnalysisVisitResp, error)
	// 添加用户访问记录
	AddVisit(ctx context.Context, in *AddVisitReq, opts ...grpc.CallOption) (*AddVisitResp, error)
	// 查询用户访问趋势
	FindVisitTrend(ctx context.Context, in *FindVisitTrendReq, opts ...grpc.CallOption) (*FindVisitTrendResp, error)
}

type websiteRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewWebsiteRpcClient(cc grpc.ClientConnInterface) WebsiteRpcClient {
	return &websiteRpcClient{cc}
}

func (c *websiteRpcClient) AnalysisVisit(ctx context.Context, in *AnalysisVisitReq, opts ...grpc.CallOption) (*AnalysisVisitResp, error) {
	out := new(AnalysisVisitResp)
	err := c.cc.Invoke(ctx, WebsiteRpc_AnalysisVisit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteRpcClient) AddVisit(ctx context.Context, in *AddVisitReq, opts ...grpc.CallOption) (*AddVisitResp, error) {
	out := new(AddVisitResp)
	err := c.cc.Invoke(ctx, WebsiteRpc_AddVisit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteRpcClient) FindVisitTrend(ctx context.Context, in *FindVisitTrendReq, opts ...grpc.CallOption) (*FindVisitTrendResp, error) {
	out := new(FindVisitTrendResp)
	err := c.cc.Invoke(ctx, WebsiteRpc_FindVisitTrend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsiteRpcServer is the server API for WebsiteRpc service.
// All implementations must embed UnimplementedWebsiteRpcServer
// for forward compatibility
type WebsiteRpcServer interface {
	// 用户日浏览量分析
	AnalysisVisit(context.Context, *AnalysisVisitReq) (*AnalysisVisitResp, error)
	// 添加用户访问记录
	AddVisit(context.Context, *AddVisitReq) (*AddVisitResp, error)
	// 查询用户访问趋势
	FindVisitTrend(context.Context, *FindVisitTrendReq) (*FindVisitTrendResp, error)
	mustEmbedUnimplementedWebsiteRpcServer()
}

// UnimplementedWebsiteRpcServer must be embedded to have forward compatible implementations.
type UnimplementedWebsiteRpcServer struct {
}

func (UnimplementedWebsiteRpcServer) AnalysisVisit(context.Context, *AnalysisVisitReq) (*AnalysisVisitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalysisVisit not implemented")
}
func (UnimplementedWebsiteRpcServer) AddVisit(context.Context, *AddVisitReq) (*AddVisitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVisit not implemented")
}
func (UnimplementedWebsiteRpcServer) FindVisitTrend(context.Context, *FindVisitTrendReq) (*FindVisitTrendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindVisitTrend not implemented")
}
func (UnimplementedWebsiteRpcServer) mustEmbedUnimplementedWebsiteRpcServer() {}

// UnsafeWebsiteRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebsiteRpcServer will
// result in compilation errors.
type UnsafeWebsiteRpcServer interface {
	mustEmbedUnimplementedWebsiteRpcServer()
}

func RegisterWebsiteRpcServer(s grpc.ServiceRegistrar, srv WebsiteRpcServer) {
	s.RegisterService(&WebsiteRpc_ServiceDesc, srv)
}

func _WebsiteRpc_AnalysisVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisVisitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteRpcServer).AnalysisVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebsiteRpc_AnalysisVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteRpcServer).AnalysisVisit(ctx, req.(*AnalysisVisitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebsiteRpc_AddVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVisitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteRpcServer).AddVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebsiteRpc_AddVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteRpcServer).AddVisit(ctx, req.(*AddVisitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebsiteRpc_FindVisitTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVisitTrendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteRpcServer).FindVisitTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebsiteRpc_FindVisitTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteRpcServer).FindVisitTrend(ctx, req.(*FindVisitTrendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WebsiteRpc_ServiceDesc is the grpc.ServiceDesc for WebsiteRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebsiteRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "websiterpc.WebsiteRpc",
	HandlerType: (*WebsiteRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalysisVisit",
			Handler:    _WebsiteRpc_AnalysisVisit_Handler,
		},
		{
			MethodName: "AddVisit",
			Handler:    _WebsiteRpc_AddVisit_Handler,
		},
		{
			MethodName: "FindVisitTrend",
			Handler:    _WebsiteRpc_FindVisitTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "website.proto",
}
