// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package server

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/logic/configrpc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/svc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/pb/blog"
)

type ConfigRpcServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedConfigRpcServer
}

func NewConfigRpcServer(svcCtx *svc.ServiceContext) *ConfigRpcServer {
	return &ConfigRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ConfigRpcServer) CreateConfig(ctx context.Context, in *blog.Config) (*blog.Config, error) {
	l := configrpclogic.NewCreateConfigLogic(ctx, s.svcCtx)
	return l.CreateConfig(in)
}

func (s *ConfigRpcServer) UpdateConfig(ctx context.Context, in *blog.Config) (*blog.Config, error) {
	l := configrpclogic.NewUpdateConfigLogic(ctx, s.svcCtx)
	return l.UpdateConfig(in)
}

func (s *ConfigRpcServer) DeleteConfig(ctx context.Context, in *blog.IdReq) (*blog.BatchResp, error) {
	l := configrpclogic.NewDeleteConfigLogic(ctx, s.svcCtx)
	return l.DeleteConfig(in)
}

func (s *ConfigRpcServer) FindConfig(ctx context.Context, in *blog.IdReq) (*blog.Config, error) {
	l := configrpclogic.NewFindConfigLogic(ctx, s.svcCtx)
	return l.FindConfig(in)
}
