// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package server

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/rpc/blog/internal/logic/uploadrpc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/rpc/blog/internal/pb/blog"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/rpc/blog/internal/svc"
)

type UploadRpcServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedUploadRpcServer
}

func NewUploadRpcServer(svcCtx *svc.ServiceContext) *UploadRpcServer {
	return &UploadRpcServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *UploadRpcServer) AddUploadRecord(ctx context.Context, in *blog.UploadRecordReq) (*blog.UploadRecordResp, error) {
	l := uploadrpclogic.NewAddUploadRecordLogic(ctx, s.svcCtx)
	return l.AddUploadRecord(in)
}
