// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

var (
	cacheTalkIdPrefix = "cache:talk:id:"
)

type (
	talkModel interface {
		// 切换事务操作
		WithTransaction(tx *gorm.DB) (out TalkModel)
		Insert(ctx context.Context, in *Talk) (*Talk, error)
		InsertBatch(ctx context.Context, in ...*Talk) (rows int64, err error)
		First(ctx context.Context, conditions string, args ...interface{}) (out *Talk, err error)
		FindCount(ctx context.Context, conditions string, args ...interface{}) (count int64, err error)
		FindALL(ctx context.Context, conditions string, args ...interface{}) (out []*Talk, err error)
		FindList(ctx context.Context, limit int, offset int, sorts string, conditions string, args ...interface{}) (out []*Talk, err error)
		FindOne(ctx context.Context, id int64) (*Talk, error)
		Update(ctx context.Context, data *Talk) (*Talk, error)
		UpdateColumns(ctx context.Context, id int64, columns map[string]interface{}) (rows int64, err error)
		Save(ctx context.Context, data *Talk) (*Talk, error)
		Delete(ctx context.Context, id int64) (rows int64, err error)
		DeleteBatch(ctx context.Context, conditions string, args ...interface{}) (rows int64, err error)
		// add extra method in here

	}

	defaultTalkModel struct {
		DbEngin    *gorm.DB
		CacheEngin *redis.Client
		table      string
	}

	Talk struct {
		Id        int64     `gorm:"column:id"`         // 说说id
		UserId    int64     `gorm:"column:user_id"`    // 用户id
		Content   string    `gorm:"column:content"`    // 说说内容
		Images    string    `gorm:"column:images"`     // 图片
		IsTop     int64     `gorm:"column:is_top"`     // 是否置顶
		Status    int64     `gorm:"column:status"`     // 状态 1.公开 2.私密
		CreatedAt time.Time `gorm:"column:created_at"` // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"` // 更新时间
	}
)

func newTalkModel(db *gorm.DB, cache *redis.Client) *defaultTalkModel {
	return &defaultTalkModel{
		DbEngin:    db,
		CacheEngin: cache,
		table:      "`talk`",
	}
}

// 切换事务操作
func (m *defaultTalkModel) WithTransaction(tx *gorm.DB) (out TalkModel) {
	return NewTalkModel(tx, m.CacheEngin)
}

// 插入Talk记录
func (m *defaultTalkModel) Insert(ctx context.Context, in *Talk) (out *Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	err = db.Create(&in).Error
	if err != nil {
		return nil, err
	}
	return in, err
}

// 插入Talk记录
func (m *defaultTalkModel) InsertBatch(ctx context.Context, in ...*Talk) (rows int64, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	err = db.CreateInBatches(&in, len(in)).Error
	if err != nil {
		return 0, err
	}
	return rows, err
}

// 更新Talk记录
func (m *defaultTalkModel) Update(ctx context.Context, in *Talk) (out *Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	err = db.Updates(&in).Error
	if err != nil {
		return nil, err
	}
	return in, err
}

// 更新Talk记录
func (m *defaultTalkModel) UpdateColumns(ctx context.Context, id int64, columns map[string]interface{}) (rows int64, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	result := db.Where("`id` = ?", id).UpdateColumns(&columns)
	if result.Error != nil {
		return 0, err
	}

	return result.RowsAffected, err
}

// 更新Talk记录
func (m *defaultTalkModel) Save(ctx context.Context, in *Talk) (out *Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	err = db.Save(&in).Error
	if err != nil {
		return nil, err
	}
	return in, err
}

// 删除Talk记录
func (m *defaultTalkModel) Delete(ctx context.Context, id int64) (rows int64, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	db = db.Where("id = ?", id)

	query := db.Delete(&Talk{})
	return query.RowsAffected, query.Error
}

// 删除Talk记录
func (m *defaultTalkModel) DeleteBatch(ctx context.Context, conditions string, args ...interface{}) (rows int64, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有条件语句
	if len(conditions) != 0 {
		db = db.Where(conditions, args...)
	}

	result := db.Delete(&Talk{})
	return result.RowsAffected, result.Error
}

// 查询Talk记录
func (m *defaultTalkModel) First(ctx context.Context, conditions string, args ...interface{}) (out *Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有条件语句
	if len(conditions) != 0 {
		db = db.Where(conditions, args...)
	}

	out = new(Talk)
	err = db.First(&out).Error
	if err != nil {
		return nil, err
	}
	return out, err
}

// 查询Talk总数
func (m *defaultTalkModel) FindCount(ctx context.Context, conditions string, args ...interface{}) (count int64, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有条件语句
	if len(conditions) != 0 {
		db = db.Where(conditions, args...)
	}

	err = db.Model(&Talk{}).Count(&count).Error
	if err != nil {
		return 0, err
	}
	return count, nil
}

// 查询Talk列表
func (m *defaultTalkModel) FindALL(ctx context.Context, conditions string, args ...interface{}) (out []*Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有条件语句
	if len(conditions) != 0 {
		db = db.Where(conditions, args...)
	}

	err = db.Find(&out).Error
	if err != nil {
		return nil, err
	}
	return out, err
}

// 分页查询Talk记录
func (m *defaultTalkModel) FindList(ctx context.Context, limit int, offset int, sorts string, conditions string, args ...interface{}) (list []*Talk, err error) {
	// 创建db
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有搜索条件
	if len(conditions) != 0 {
		db = db.Where(conditions, args...)
	}

	// 如果有排序参数
	if len(sorts) != 0 {
		db = db.Order(sorts)
	}

	// 如果有分页参数
	if limit > 0 && offset > 0 {
		db = db.Limit(limit).Offset(offset)
	}

	// 查询数据
	err = db.Find(&list).Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// 查询Talk记录
func (m *defaultTalkModel) FindOne(ctx context.Context, id int64) (out *Talk, err error) {
	db := m.DbEngin.WithContext(ctx).Table(m.table)

	// 如果有条件语句
	err = db.Where("`id` = ?", id).First(&out).Error
	if err != nil {
		return nil, err
	}

	return out, err
}

func (m *defaultTalkModel) TableName() string {
	return m.table
}
