// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: discussion.proto

package discussionservice

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"

	"github.com/ve-weiyi/ve-blog-golang/service/app/rpc/internal/pb/discussionrpc"
)

type (
	BatchUpdateCommentStatusRequest  = discussionrpc.BatchUpdateCommentStatusRequest
	BatchUpdateCommentStatusResponse = discussionrpc.BatchUpdateCommentStatusResponse
	BatchUpdateMessageStatusRequest  = discussionrpc.BatchUpdateMessageStatusRequest
	BatchUpdateMessageStatusResponse = discussionrpc.BatchUpdateMessageStatusResponse
	Chat                             = discussionrpc.Chat
	Comment                          = discussionrpc.Comment
	CreateChatRequest                = discussionrpc.CreateChatRequest
	CreateChatResponse               = discussionrpc.CreateChatResponse
	CreateCommentRequest             = discussionrpc.CreateCommentRequest
	CreateCommentResponse            = discussionrpc.CreateCommentResponse
	CreateMessageRequest             = discussionrpc.CreateMessageRequest
	CreateMessageResponse            = discussionrpc.CreateMessageResponse
	DeleteChatRequest                = discussionrpc.DeleteChatRequest
	DeleteChatResponse               = discussionrpc.DeleteChatResponse
	DeleteCommentRequest             = discussionrpc.DeleteCommentRequest
	DeleteCommentResponse            = discussionrpc.DeleteCommentResponse
	DeleteMessageRequest             = discussionrpc.DeleteMessageRequest
	DeleteMessageResponse            = discussionrpc.DeleteMessageResponse
	GetChatRequest                   = discussionrpc.GetChatRequest
	GetChatResponse                  = discussionrpc.GetChatResponse
	GetCommentReplyCountRequest      = discussionrpc.GetCommentReplyCountRequest
	GetCommentReplyCountResponse     = discussionrpc.GetCommentReplyCountResponse
	GetCommentRequest                = discussionrpc.GetCommentRequest
	GetCommentResponse               = discussionrpc.GetCommentResponse
	GetMessageRequest                = discussionrpc.GetMessageRequest
	GetMessageResponse               = discussionrpc.GetMessageResponse
	GetUserLikeCommentRequest        = discussionrpc.GetUserLikeCommentRequest
	GetUserLikeCommentResponse       = discussionrpc.GetUserLikeCommentResponse
	LikeCommentRequest               = discussionrpc.LikeCommentRequest
	LikeCommentResponse              = discussionrpc.LikeCommentResponse
	ListChatsRequest                 = discussionrpc.ListChatsRequest
	ListChatsResponse                = discussionrpc.ListChatsResponse
	ListCommentRepliesRequest        = discussionrpc.ListCommentRepliesRequest
	ListCommentRepliesResponse       = discussionrpc.ListCommentRepliesResponse
	ListCommentsRequest              = discussionrpc.ListCommentsRequest
	ListCommentsResponse             = discussionrpc.ListCommentsResponse
	ListMessagesRequest              = discussionrpc.ListMessagesRequest
	ListMessagesResponse             = discussionrpc.ListMessagesResponse
	Message                          = discussionrpc.Message
	PageQuery                        = discussionrpc.PageQuery
	PageResult                       = discussionrpc.PageResult
	UpdateChatRequest                = discussionrpc.UpdateChatRequest
	UpdateChatResponse               = discussionrpc.UpdateChatResponse
	UpdateCommentRequest             = discussionrpc.UpdateCommentRequest
	UpdateCommentResponse            = discussionrpc.UpdateCommentResponse
	UpdateMessageRequest             = discussionrpc.UpdateMessageRequest
	UpdateMessageResponse            = discussionrpc.UpdateMessageResponse

	DiscussionService interface {
		// 查询聊天记录列表
		ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
		// 查询聊天记录
		GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error)
		// 创建聊天记录
		CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error)
		// 更新聊天记录
		UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*UpdateChatResponse, error)
		// 批量删除聊天记录
		DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error)
		// 查询留言列表
		ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		// 查询留言
		GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
		// 创建留言
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
		// 更新留言
		UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
		// 批量删除留言
		DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
		// 批量更新留言状态
		BatchUpdateMessageStatus(ctx context.Context, in *BatchUpdateMessageStatusRequest, opts ...grpc.CallOption) (*BatchUpdateMessageStatusResponse, error)
		// 查询评论列表
		ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
		// 查询评论回复列表
		ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error)
		// 查询评论
		GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
		// 创建评论
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		// 更新评论
		UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
		// 批量删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
		// 批量更新评论状态
		BatchUpdateCommentStatus(ctx context.Context, in *BatchUpdateCommentStatusRequest, opts ...grpc.CallOption) (*BatchUpdateCommentStatusResponse, error)
		// 查询评论回复数量
		GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error)
		// 点赞评论
		LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
		// 查询用户点赞的评论
		GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error)
	}

	defaultDiscussionService struct {
		cli zrpc.Client
	}
)

func NewDiscussionService(cli zrpc.Client) DiscussionService {
	return &defaultDiscussionService{
		cli: cli,
	}
}

// 查询聊天记录列表
func (m *defaultDiscussionService) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListChats(ctx, in, opts...)
}

// 查询聊天记录
func (m *defaultDiscussionService) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetChat(ctx, in, opts...)
}

// 创建聊天记录
func (m *defaultDiscussionService) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateChat(ctx, in, opts...)
}

// 更新聊天记录
func (m *defaultDiscussionService) UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*UpdateChatResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateChat(ctx, in, opts...)
}

// 批量删除聊天记录
func (m *defaultDiscussionService) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.DeleteChat(ctx, in, opts...)
}

// 查询留言列表
func (m *defaultDiscussionService) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

// 查询留言
func (m *defaultDiscussionService) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetMessage(ctx, in, opts...)
}

// 创建留言
func (m *defaultDiscussionService) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

// 更新留言
func (m *defaultDiscussionService) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateMessage(ctx, in, opts...)
}

// 批量删除留言
func (m *defaultDiscussionService) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.DeleteMessage(ctx, in, opts...)
}

// 批量更新留言状态
func (m *defaultDiscussionService) BatchUpdateMessageStatus(ctx context.Context, in *BatchUpdateMessageStatusRequest, opts ...grpc.CallOption) (*BatchUpdateMessageStatusResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchUpdateMessageStatus(ctx, in, opts...)
}

// 查询评论列表
func (m *defaultDiscussionService) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

// 查询评论回复列表
func (m *defaultDiscussionService) ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListCommentReplies(ctx, in, opts...)
}

// 查询评论
func (m *defaultDiscussionService) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetComment(ctx, in, opts...)
}

// 创建评论
func (m *defaultDiscussionService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 更新评论
func (m *defaultDiscussionService) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateComment(ctx, in, opts...)
}

// 批量删除评论
func (m *defaultDiscussionService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 批量更新评论状态
func (m *defaultDiscussionService) BatchUpdateCommentStatus(ctx context.Context, in *BatchUpdateCommentStatusRequest, opts ...grpc.CallOption) (*BatchUpdateCommentStatusResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchUpdateCommentStatus(ctx, in, opts...)
}

// 查询评论回复数量
func (m *defaultDiscussionService) GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetCommentReplyCount(ctx, in, opts...)
}

// 点赞评论
func (m *defaultDiscussionService) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

// 查询用户点赞的评论
func (m *defaultDiscussionService) GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetUserLikeComment(ctx, in, opts...)
}
