// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: message.proto

// proto 包名

package messagerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageRpc_AnalysisMessage_FullMethodName        = "/messagerpc.MessageRpc/AnalysisMessage"
	MessageRpc_AddChat_FullMethodName                = "/messagerpc.MessageRpc/AddChat"
	MessageRpc_UpdateChat_FullMethodName             = "/messagerpc.MessageRpc/UpdateChat"
	MessageRpc_GetChat_FullMethodName                = "/messagerpc.MessageRpc/GetChat"
	MessageRpc_DeletesChat_FullMethodName            = "/messagerpc.MessageRpc/DeletesChat"
	MessageRpc_FindChatList_FullMethodName           = "/messagerpc.MessageRpc/FindChatList"
	MessageRpc_AddRemark_FullMethodName              = "/messagerpc.MessageRpc/AddRemark"
	MessageRpc_UpdateRemark_FullMethodName           = "/messagerpc.MessageRpc/UpdateRemark"
	MessageRpc_GetRemark_FullMethodName              = "/messagerpc.MessageRpc/GetRemark"
	MessageRpc_DeletesRemark_FullMethodName          = "/messagerpc.MessageRpc/DeletesRemark"
	MessageRpc_FindRemarkList_FullMethodName         = "/messagerpc.MessageRpc/FindRemarkList"
	MessageRpc_UpdateRemarkStatus_FullMethodName     = "/messagerpc.MessageRpc/UpdateRemarkStatus"
	MessageRpc_AddComment_FullMethodName             = "/messagerpc.MessageRpc/AddComment"
	MessageRpc_UpdateComment_FullMethodName          = "/messagerpc.MessageRpc/UpdateComment"
	MessageRpc_GetComment_FullMethodName             = "/messagerpc.MessageRpc/GetComment"
	MessageRpc_DeletesComment_FullMethodName         = "/messagerpc.MessageRpc/DeletesComment"
	MessageRpc_FindCommentList_FullMethodName        = "/messagerpc.MessageRpc/FindCommentList"
	MessageRpc_FindCommentReplyList_FullMethodName   = "/messagerpc.MessageRpc/FindCommentReplyList"
	MessageRpc_FindCommentReplyCounts_FullMethodName = "/messagerpc.MessageRpc/FindCommentReplyCounts"
	MessageRpc_UpdateCommentStatus_FullMethodName    = "/messagerpc.MessageRpc/UpdateCommentStatus"
	MessageRpc_LikeComment_FullMethodName            = "/messagerpc.MessageRpc/LikeComment"
	MessageRpc_FindUserLikeComment_FullMethodName    = "/messagerpc.MessageRpc/FindUserLikeComment"
)

// MessageRpcClient is the client API for MessageRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageRpcClient interface {
	// 消息数据分析
	AnalysisMessage(ctx context.Context, in *AnalysisMessageReq, opts ...grpc.CallOption) (*AnalysisMessageResp, error)
	// 创建聊天记录
	AddChat(ctx context.Context, in *AddChatReq, opts ...grpc.CallOption) (*ChatDetailsResp, error)
	// 更新聊天记录
	UpdateChat(ctx context.Context, in *UpdateChatReq, opts ...grpc.CallOption) (*ChatDetailsResp, error)
	// 查询聊天记录
	GetChat(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ChatDetailsResp, error)
	// 删除聊天记录
	DeletesChat(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
	// 查询聊天记录列表
	FindChatList(ctx context.Context, in *FindChatListReq, opts ...grpc.CallOption) (*FindChatListResp, error)
	// 创建留言
	AddRemark(ctx context.Context, in *AddRemarkReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error)
	// 更新留言
	UpdateRemark(ctx context.Context, in *UpdateRemarkReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error)
	// 查询留言
	GetRemark(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error)
	// 删除留言
	DeletesRemark(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
	// 查询留言列表
	FindRemarkList(ctx context.Context, in *FindRemarkListReq, opts ...grpc.CallOption) (*FindRemarkListResp, error)
	// 更新留言状态
	UpdateRemarkStatus(ctx context.Context, in *UpdateRemarkStatusReq, opts ...grpc.CallOption) (*BatchResp, error)
	// 创建评论
	AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*CommentDetailsResp, error)
	// 更新评论
	UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*CommentDetailsResp, error)
	// 查询评论
	GetComment(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CommentDetailsResp, error)
	// 删除评论
	DeletesComment(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
	// 查询评论列表
	FindCommentList(ctx context.Context, in *FindCommentListReq, opts ...grpc.CallOption) (*FindCommentListResp, error)
	// 查询评论回复列表
	FindCommentReplyList(ctx context.Context, in *FindCommentReplyListReq, opts ...grpc.CallOption) (*FindCommentReplyListResp, error)
	// 查询评论回复数量
	FindCommentReplyCounts(ctx context.Context, in *FindCommentReplyCountsReq, opts ...grpc.CallOption) (*FindCommentReplyCountsResp, error)
	// 更新评论状态
	UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*BatchResp, error)
	// 点赞评论
	LikeComment(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 用户点赞的评论
	FindUserLikeComment(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindLikeCommentResp, error)
}

type messageRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageRpcClient(cc grpc.ClientConnInterface) MessageRpcClient {
	return &messageRpcClient{cc}
}

func (c *messageRpcClient) AnalysisMessage(ctx context.Context, in *AnalysisMessageReq, opts ...grpc.CallOption) (*AnalysisMessageResp, error) {
	out := new(AnalysisMessageResp)
	err := c.cc.Invoke(ctx, MessageRpc_AnalysisMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) AddChat(ctx context.Context, in *AddChatReq, opts ...grpc.CallOption) (*ChatDetailsResp, error) {
	out := new(ChatDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_AddChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateChat(ctx context.Context, in *UpdateChatReq, opts ...grpc.CallOption) (*ChatDetailsResp, error) {
	out := new(ChatDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetChat(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ChatDetailsResp, error) {
	out := new(ChatDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) DeletesChat(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	out := new(BatchResp)
	err := c.cc.Invoke(ctx, MessageRpc_DeletesChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindChatList(ctx context.Context, in *FindChatListReq, opts ...grpc.CallOption) (*FindChatListResp, error) {
	out := new(FindChatListResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindChatList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) AddRemark(ctx context.Context, in *AddRemarkReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error) {
	out := new(RemarkDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_AddRemark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateRemark(ctx context.Context, in *UpdateRemarkReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error) {
	out := new(RemarkDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateRemark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetRemark(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RemarkDetailsResp, error) {
	out := new(RemarkDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetRemark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) DeletesRemark(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	out := new(BatchResp)
	err := c.cc.Invoke(ctx, MessageRpc_DeletesRemark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindRemarkList(ctx context.Context, in *FindRemarkListReq, opts ...grpc.CallOption) (*FindRemarkListResp, error) {
	out := new(FindRemarkListResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindRemarkList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateRemarkStatus(ctx context.Context, in *UpdateRemarkStatusReq, opts ...grpc.CallOption) (*BatchResp, error) {
	out := new(BatchResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateRemarkStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*CommentDetailsResp, error) {
	out := new(CommentDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_AddComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*CommentDetailsResp, error) {
	out := new(CommentDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetComment(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CommentDetailsResp, error) {
	out := new(CommentDetailsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) DeletesComment(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	out := new(BatchResp)
	err := c.cc.Invoke(ctx, MessageRpc_DeletesComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindCommentList(ctx context.Context, in *FindCommentListReq, opts ...grpc.CallOption) (*FindCommentListResp, error) {
	out := new(FindCommentListResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindCommentList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindCommentReplyList(ctx context.Context, in *FindCommentReplyListReq, opts ...grpc.CallOption) (*FindCommentReplyListResp, error) {
	out := new(FindCommentReplyListResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindCommentReplyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindCommentReplyCounts(ctx context.Context, in *FindCommentReplyCountsReq, opts ...grpc.CallOption) (*FindCommentReplyCountsResp, error) {
	out := new(FindCommentReplyCountsResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindCommentReplyCounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*BatchResp, error) {
	out := new(BatchResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateCommentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) LikeComment(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, MessageRpc_LikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) FindUserLikeComment(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindLikeCommentResp, error) {
	out := new(FindLikeCommentResp)
	err := c.cc.Invoke(ctx, MessageRpc_FindUserLikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageRpcServer is the server API for MessageRpc service.
// All implementations must embed UnimplementedMessageRpcServer
// for forward compatibility
type MessageRpcServer interface {
	// 消息数据分析
	AnalysisMessage(context.Context, *AnalysisMessageReq) (*AnalysisMessageResp, error)
	// 创建聊天记录
	AddChat(context.Context, *AddChatReq) (*ChatDetailsResp, error)
	// 更新聊天记录
	UpdateChat(context.Context, *UpdateChatReq) (*ChatDetailsResp, error)
	// 查询聊天记录
	GetChat(context.Context, *IdReq) (*ChatDetailsResp, error)
	// 删除聊天记录
	DeletesChat(context.Context, *IdsReq) (*BatchResp, error)
	// 查询聊天记录列表
	FindChatList(context.Context, *FindChatListReq) (*FindChatListResp, error)
	// 创建留言
	AddRemark(context.Context, *AddRemarkReq) (*RemarkDetailsResp, error)
	// 更新留言
	UpdateRemark(context.Context, *UpdateRemarkReq) (*RemarkDetailsResp, error)
	// 查询留言
	GetRemark(context.Context, *IdReq) (*RemarkDetailsResp, error)
	// 删除留言
	DeletesRemark(context.Context, *IdsReq) (*BatchResp, error)
	// 查询留言列表
	FindRemarkList(context.Context, *FindRemarkListReq) (*FindRemarkListResp, error)
	// 更新留言状态
	UpdateRemarkStatus(context.Context, *UpdateRemarkStatusReq) (*BatchResp, error)
	// 创建评论
	AddComment(context.Context, *AddCommentReq) (*CommentDetailsResp, error)
	// 更新评论
	UpdateComment(context.Context, *UpdateCommentReq) (*CommentDetailsResp, error)
	// 查询评论
	GetComment(context.Context, *IdReq) (*CommentDetailsResp, error)
	// 删除评论
	DeletesComment(context.Context, *IdsReq) (*BatchResp, error)
	// 查询评论列表
	FindCommentList(context.Context, *FindCommentListReq) (*FindCommentListResp, error)
	// 查询评论回复列表
	FindCommentReplyList(context.Context, *FindCommentReplyListReq) (*FindCommentReplyListResp, error)
	// 查询评论回复数量
	FindCommentReplyCounts(context.Context, *FindCommentReplyCountsReq) (*FindCommentReplyCountsResp, error)
	// 更新评论状态
	UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*BatchResp, error)
	// 点赞评论
	LikeComment(context.Context, *IdReq) (*EmptyResp, error)
	// 用户点赞的评论
	FindUserLikeComment(context.Context, *UserIdReq) (*FindLikeCommentResp, error)
	mustEmbedUnimplementedMessageRpcServer()
}

// UnimplementedMessageRpcServer must be embedded to have forward compatible implementations.
type UnimplementedMessageRpcServer struct {
}

func (UnimplementedMessageRpcServer) AnalysisMessage(context.Context, *AnalysisMessageReq) (*AnalysisMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalysisMessage not implemented")
}
func (UnimplementedMessageRpcServer) AddChat(context.Context, *AddChatReq) (*ChatDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChat not implemented")
}
func (UnimplementedMessageRpcServer) UpdateChat(context.Context, *UpdateChatReq) (*ChatDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChat not implemented")
}
func (UnimplementedMessageRpcServer) GetChat(context.Context, *IdReq) (*ChatDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedMessageRpcServer) DeletesChat(context.Context, *IdsReq) (*BatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesChat not implemented")
}
func (UnimplementedMessageRpcServer) FindChatList(context.Context, *FindChatListReq) (*FindChatListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindChatList not implemented")
}
func (UnimplementedMessageRpcServer) AddRemark(context.Context, *AddRemarkReq) (*RemarkDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRemark not implemented")
}
func (UnimplementedMessageRpcServer) UpdateRemark(context.Context, *UpdateRemarkReq) (*RemarkDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemark not implemented")
}
func (UnimplementedMessageRpcServer) GetRemark(context.Context, *IdReq) (*RemarkDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemark not implemented")
}
func (UnimplementedMessageRpcServer) DeletesRemark(context.Context, *IdsReq) (*BatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesRemark not implemented")
}
func (UnimplementedMessageRpcServer) FindRemarkList(context.Context, *FindRemarkListReq) (*FindRemarkListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRemarkList not implemented")
}
func (UnimplementedMessageRpcServer) UpdateRemarkStatus(context.Context, *UpdateRemarkStatusReq) (*BatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemarkStatus not implemented")
}
func (UnimplementedMessageRpcServer) AddComment(context.Context, *AddCommentReq) (*CommentDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedMessageRpcServer) UpdateComment(context.Context, *UpdateCommentReq) (*CommentDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedMessageRpcServer) GetComment(context.Context, *IdReq) (*CommentDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedMessageRpcServer) DeletesComment(context.Context, *IdsReq) (*BatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesComment not implemented")
}
func (UnimplementedMessageRpcServer) FindCommentList(context.Context, *FindCommentListReq) (*FindCommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentList not implemented")
}
func (UnimplementedMessageRpcServer) FindCommentReplyList(context.Context, *FindCommentReplyListReq) (*FindCommentReplyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentReplyList not implemented")
}
func (UnimplementedMessageRpcServer) FindCommentReplyCounts(context.Context, *FindCommentReplyCountsReq) (*FindCommentReplyCountsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentReplyCounts not implemented")
}
func (UnimplementedMessageRpcServer) UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*BatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommentStatus not implemented")
}
func (UnimplementedMessageRpcServer) LikeComment(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedMessageRpcServer) FindUserLikeComment(context.Context, *UserIdReq) (*FindLikeCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserLikeComment not implemented")
}
func (UnimplementedMessageRpcServer) mustEmbedUnimplementedMessageRpcServer() {}

// UnsafeMessageRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageRpcServer will
// result in compilation errors.
type UnsafeMessageRpcServer interface {
	mustEmbedUnimplementedMessageRpcServer()
}

func RegisterMessageRpcServer(s grpc.ServiceRegistrar, srv MessageRpcServer) {
	s.RegisterService(&MessageRpc_ServiceDesc, srv)
}

func _MessageRpc_AnalysisMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).AnalysisMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_AnalysisMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).AnalysisMessage(ctx, req.(*AnalysisMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_AddChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).AddChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_AddChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).AddChat(ctx, req.(*AddChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateChat(ctx, req.(*UpdateChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetChat(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_DeletesChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).DeletesChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_DeletesChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).DeletesChat(ctx, req.(*IdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindChatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindChatList(ctx, req.(*FindChatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_AddRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).AddRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_AddRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).AddRemark(ctx, req.(*AddRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateRemark(ctx, req.(*UpdateRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetRemark(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_DeletesRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).DeletesRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_DeletesRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).DeletesRemark(ctx, req.(*IdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindRemarkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRemarkListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindRemarkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindRemarkList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindRemarkList(ctx, req.(*FindRemarkListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateRemarkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemarkStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateRemarkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateRemarkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateRemarkStatus(ctx, req.(*UpdateRemarkStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).AddComment(ctx, req.(*AddCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateComment(ctx, req.(*UpdateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetComment(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_DeletesComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).DeletesComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_DeletesComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).DeletesComment(ctx, req.(*IdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindCommentList(ctx, req.(*FindCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindCommentReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentReplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindCommentReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindCommentReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindCommentReplyList(ctx, req.(*FindCommentReplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindCommentReplyCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentReplyCountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindCommentReplyCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindCommentReplyCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindCommentReplyCounts(ctx, req.(*FindCommentReplyCountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateCommentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateCommentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateCommentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateCommentStatus(ctx, req.(*UpdateCommentStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).LikeComment(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_FindUserLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).FindUserLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_FindUserLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).FindUserLikeComment(ctx, req.(*UserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageRpc_ServiceDesc is the grpc.ServiceDesc for MessageRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messagerpc.MessageRpc",
	HandlerType: (*MessageRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalysisMessage",
			Handler:    _MessageRpc_AnalysisMessage_Handler,
		},
		{
			MethodName: "AddChat",
			Handler:    _MessageRpc_AddChat_Handler,
		},
		{
			MethodName: "UpdateChat",
			Handler:    _MessageRpc_UpdateChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _MessageRpc_GetChat_Handler,
		},
		{
			MethodName: "DeletesChat",
			Handler:    _MessageRpc_DeletesChat_Handler,
		},
		{
			MethodName: "FindChatList",
			Handler:    _MessageRpc_FindChatList_Handler,
		},
		{
			MethodName: "AddRemark",
			Handler:    _MessageRpc_AddRemark_Handler,
		},
		{
			MethodName: "UpdateRemark",
			Handler:    _MessageRpc_UpdateRemark_Handler,
		},
		{
			MethodName: "GetRemark",
			Handler:    _MessageRpc_GetRemark_Handler,
		},
		{
			MethodName: "DeletesRemark",
			Handler:    _MessageRpc_DeletesRemark_Handler,
		},
		{
			MethodName: "FindRemarkList",
			Handler:    _MessageRpc_FindRemarkList_Handler,
		},
		{
			MethodName: "UpdateRemarkStatus",
			Handler:    _MessageRpc_UpdateRemarkStatus_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _MessageRpc_AddComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _MessageRpc_UpdateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _MessageRpc_GetComment_Handler,
		},
		{
			MethodName: "DeletesComment",
			Handler:    _MessageRpc_DeletesComment_Handler,
		},
		{
			MethodName: "FindCommentList",
			Handler:    _MessageRpc_FindCommentList_Handler,
		},
		{
			MethodName: "FindCommentReplyList",
			Handler:    _MessageRpc_FindCommentReplyList_Handler,
		},
		{
			MethodName: "FindCommentReplyCounts",
			Handler:    _MessageRpc_FindCommentReplyCounts_Handler,
		},
		{
			MethodName: "UpdateCommentStatus",
			Handler:    _MessageRpc_UpdateCommentStatus_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _MessageRpc_LikeComment_Handler,
		},
		{
			MethodName: "FindUserLikeComment",
			Handler:    _MessageRpc_FindUserLikeComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
