// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: permission.proto

// proto 包名

package permissionrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PermissionRpc_AddApi_FullMethodName            = "/permissionrpc.PermissionRpc/AddApi"
	PermissionRpc_UpdateApi_FullMethodName         = "/permissionrpc.PermissionRpc/UpdateApi"
	PermissionRpc_DeletesApi_FullMethodName        = "/permissionrpc.PermissionRpc/DeletesApi"
	PermissionRpc_FindApiList_FullMethodName       = "/permissionrpc.PermissionRpc/FindApiList"
	PermissionRpc_SyncApiList_FullMethodName       = "/permissionrpc.PermissionRpc/SyncApiList"
	PermissionRpc_CleanApiList_FullMethodName      = "/permissionrpc.PermissionRpc/CleanApiList"
	PermissionRpc_FindAllApi_FullMethodName        = "/permissionrpc.PermissionRpc/FindAllApi"
	PermissionRpc_AddMenu_FullMethodName           = "/permissionrpc.PermissionRpc/AddMenu"
	PermissionRpc_UpdateMenu_FullMethodName        = "/permissionrpc.PermissionRpc/UpdateMenu"
	PermissionRpc_DeletesMenu_FullMethodName       = "/permissionrpc.PermissionRpc/DeletesMenu"
	PermissionRpc_FindMenuList_FullMethodName      = "/permissionrpc.PermissionRpc/FindMenuList"
	PermissionRpc_SyncMenuList_FullMethodName      = "/permissionrpc.PermissionRpc/SyncMenuList"
	PermissionRpc_CleanMenuList_FullMethodName     = "/permissionrpc.PermissionRpc/CleanMenuList"
	PermissionRpc_FindAllMenu_FullMethodName       = "/permissionrpc.PermissionRpc/FindAllMenu"
	PermissionRpc_AddRole_FullMethodName           = "/permissionrpc.PermissionRpc/AddRole"
	PermissionRpc_UpdateRole_FullMethodName        = "/permissionrpc.PermissionRpc/UpdateRole"
	PermissionRpc_DeletesRole_FullMethodName       = "/permissionrpc.PermissionRpc/DeletesRole"
	PermissionRpc_FindRoleList_FullMethodName      = "/permissionrpc.PermissionRpc/FindRoleList"
	PermissionRpc_FindAllRole_FullMethodName       = "/permissionrpc.PermissionRpc/FindAllRole"
	PermissionRpc_UpdateRoleMenus_FullMethodName   = "/permissionrpc.PermissionRpc/UpdateRoleMenus"
	PermissionRpc_UpdateRoleApis_FullMethodName    = "/permissionrpc.PermissionRpc/UpdateRoleApis"
	PermissionRpc_FindRoleResources_FullMethodName = "/permissionrpc.PermissionRpc/FindRoleResources"
	PermissionRpc_UpdateUserRole_FullMethodName    = "/permissionrpc.PermissionRpc/UpdateUserRole"
	PermissionRpc_FindUserApis_FullMethodName      = "/permissionrpc.PermissionRpc/FindUserApis"
	PermissionRpc_FindUserMenus_FullMethodName     = "/permissionrpc.PermissionRpc/FindUserMenus"
	PermissionRpc_FindUserRoles_FullMethodName     = "/permissionrpc.PermissionRpc/FindUserRoles"
)

// PermissionRpcClient is the client API for PermissionRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionRpcClient interface {
	// 创建接口
	AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiResp, error)
	// 更新接口
	UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiResp, error)
	// 删除接口
	DeletesApi(ctx context.Context, in *DeletesApiReq, opts ...grpc.CallOption) (*DeletesApiResp, error)
	// 查询接口列表
	FindApiList(ctx context.Context, in *FindApiListReq, opts ...grpc.CallOption) (*FindApiListResp, error)
	// 同步接口列表
	SyncApiList(ctx context.Context, in *SyncApiListReq, opts ...grpc.CallOption) (*SyncApiListResp, error)
	// 清空接口列表
	CleanApiList(ctx context.Context, in *CleanApiListReq, opts ...grpc.CallOption) (*CleanApiListResp, error)
	// 查找所有接口
	FindAllApi(ctx context.Context, in *FindAllApiReq, opts ...grpc.CallOption) (*FindAllApiResp, error)
	// 创建菜单
	AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error)
	// 更新菜单
	UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error)
	// 删除菜单
	DeletesMenu(ctx context.Context, in *DeletesMenuReq, opts ...grpc.CallOption) (*DeletesMenuResp, error)
	// 查询菜单列表
	FindMenuList(ctx context.Context, in *FindMenuListReq, opts ...grpc.CallOption) (*FindMenuListResp, error)
	// 同步菜单列表
	SyncMenuList(ctx context.Context, in *SyncMenuListReq, opts ...grpc.CallOption) (*SyncMenuListResp, error)
	// 清空菜单列表
	CleanMenuList(ctx context.Context, in *CleanMenuListReq, opts ...grpc.CallOption) (*CleanMenuListResp, error)
	// 查找所有菜单
	FindAllMenu(ctx context.Context, in *FindAllMenuReq, opts ...grpc.CallOption) (*FindAllMenuResp, error)
	// 创建角色
	AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error)
	// 更新角色
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
	// 删除角色
	DeletesRole(ctx context.Context, in *DeletesRoleReq, opts ...grpc.CallOption) (*DeletesRoleResp, error)
	// 查询角色列表
	FindRoleList(ctx context.Context, in *FindRoleListReq, opts ...grpc.CallOption) (*FindRoleListResp, error)
	// 查询所有角色
	FindAllRole(ctx context.Context, in *FindAllRoleReq, opts ...grpc.CallOption) (*FindAllRoleResp, error)
	// 更新角色菜单
	UpdateRoleMenus(ctx context.Context, in *UpdateRoleMenusReq, opts ...grpc.CallOption) (*UpdateRoleMenusResp, error)
	// 更新角色资源
	UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*UpdateRoleApisResp, error)
	// 查询角色资源权限
	FindRoleResources(ctx context.Context, in *FindRoleResourcesReq, opts ...grpc.CallOption) (*FindRoleResourcesResp, error)
	// 修改用户角色
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error)
	// 获取用户接口权限
	FindUserApis(ctx context.Context, in *FindUserApisReq, opts ...grpc.CallOption) (*FindUserApisResp, error)
	// 获取用户菜单权限
	FindUserMenus(ctx context.Context, in *FindUserMenusReq, opts ...grpc.CallOption) (*FindUserMenusResp, error)
	// 获取用户角色信息
	FindUserRoles(ctx context.Context, in *FindUserRolesReq, opts ...grpc.CallOption) (*FindUserRolesResp, error)
}

type permissionRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionRpcClient(cc grpc.ClientConnInterface) PermissionRpcClient {
	return &permissionRpcClient{cc}
}

func (c *permissionRpcClient) AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiResp, error) {
	out := new(AddApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_AddApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiResp, error) {
	out := new(UpdateApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) DeletesApi(ctx context.Context, in *DeletesApiReq, opts ...grpc.CallOption) (*DeletesApiResp, error) {
	out := new(DeletesApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_DeletesApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindApiList(ctx context.Context, in *FindApiListReq, opts ...grpc.CallOption) (*FindApiListResp, error) {
	out := new(FindApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindApiList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) SyncApiList(ctx context.Context, in *SyncApiListReq, opts ...grpc.CallOption) (*SyncApiListResp, error) {
	out := new(SyncApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_SyncApiList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) CleanApiList(ctx context.Context, in *CleanApiListReq, opts ...grpc.CallOption) (*CleanApiListResp, error) {
	out := new(CleanApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_CleanApiList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindAllApi(ctx context.Context, in *FindAllApiReq, opts ...grpc.CallOption) (*FindAllApiResp, error) {
	out := new(FindAllApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindAllApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error) {
	out := new(AddMenuResp)
	err := c.cc.Invoke(ctx, PermissionRpc_AddMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error) {
	out := new(UpdateMenuResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) DeletesMenu(ctx context.Context, in *DeletesMenuReq, opts ...grpc.CallOption) (*DeletesMenuResp, error) {
	out := new(DeletesMenuResp)
	err := c.cc.Invoke(ctx, PermissionRpc_DeletesMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindMenuList(ctx context.Context, in *FindMenuListReq, opts ...grpc.CallOption) (*FindMenuListResp, error) {
	out := new(FindMenuListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindMenuList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) SyncMenuList(ctx context.Context, in *SyncMenuListReq, opts ...grpc.CallOption) (*SyncMenuListResp, error) {
	out := new(SyncMenuListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_SyncMenuList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) CleanMenuList(ctx context.Context, in *CleanMenuListReq, opts ...grpc.CallOption) (*CleanMenuListResp, error) {
	out := new(CleanMenuListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_CleanMenuList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindAllMenu(ctx context.Context, in *FindAllMenuReq, opts ...grpc.CallOption) (*FindAllMenuResp, error) {
	out := new(FindAllMenuResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindAllMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error) {
	out := new(AddRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_AddRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	out := new(UpdateRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) DeletesRole(ctx context.Context, in *DeletesRoleReq, opts ...grpc.CallOption) (*DeletesRoleResp, error) {
	out := new(DeletesRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_DeletesRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindRoleList(ctx context.Context, in *FindRoleListReq, opts ...grpc.CallOption) (*FindRoleListResp, error) {
	out := new(FindRoleListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindRoleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindAllRole(ctx context.Context, in *FindAllRoleReq, opts ...grpc.CallOption) (*FindAllRoleResp, error) {
	out := new(FindAllRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindAllRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateRoleMenus(ctx context.Context, in *UpdateRoleMenusReq, opts ...grpc.CallOption) (*UpdateRoleMenusResp, error) {
	out := new(UpdateRoleMenusResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateRoleMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*UpdateRoleApisResp, error) {
	out := new(UpdateRoleApisResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateRoleApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindRoleResources(ctx context.Context, in *FindRoleResourcesReq, opts ...grpc.CallOption) (*FindRoleResourcesResp, error) {
	out := new(FindRoleResourcesResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindRoleResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error) {
	out := new(UpdateUserRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateUserRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindUserApis(ctx context.Context, in *FindUserApisReq, opts ...grpc.CallOption) (*FindUserApisResp, error) {
	out := new(FindUserApisResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindUserApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindUserMenus(ctx context.Context, in *FindUserMenusReq, opts ...grpc.CallOption) (*FindUserMenusResp, error) {
	out := new(FindUserMenusResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindUserMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindUserRoles(ctx context.Context, in *FindUserRolesReq, opts ...grpc.CallOption) (*FindUserRolesResp, error) {
	out := new(FindUserRolesResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindUserRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionRpcServer is the server API for PermissionRpc service.
// All implementations must embed UnimplementedPermissionRpcServer
// for forward compatibility
type PermissionRpcServer interface {
	// 创建接口
	AddApi(context.Context, *AddApiReq) (*AddApiResp, error)
	// 更新接口
	UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiResp, error)
	// 删除接口
	DeletesApi(context.Context, *DeletesApiReq) (*DeletesApiResp, error)
	// 查询接口列表
	FindApiList(context.Context, *FindApiListReq) (*FindApiListResp, error)
	// 同步接口列表
	SyncApiList(context.Context, *SyncApiListReq) (*SyncApiListResp, error)
	// 清空接口列表
	CleanApiList(context.Context, *CleanApiListReq) (*CleanApiListResp, error)
	// 查找所有接口
	FindAllApi(context.Context, *FindAllApiReq) (*FindAllApiResp, error)
	// 创建菜单
	AddMenu(context.Context, *AddMenuReq) (*AddMenuResp, error)
	// 更新菜单
	UpdateMenu(context.Context, *UpdateMenuReq) (*UpdateMenuResp, error)
	// 删除菜单
	DeletesMenu(context.Context, *DeletesMenuReq) (*DeletesMenuResp, error)
	// 查询菜单列表
	FindMenuList(context.Context, *FindMenuListReq) (*FindMenuListResp, error)
	// 同步菜单列表
	SyncMenuList(context.Context, *SyncMenuListReq) (*SyncMenuListResp, error)
	// 清空菜单列表
	CleanMenuList(context.Context, *CleanMenuListReq) (*CleanMenuListResp, error)
	// 查找所有菜单
	FindAllMenu(context.Context, *FindAllMenuReq) (*FindAllMenuResp, error)
	// 创建角色
	AddRole(context.Context, *AddRoleReq) (*AddRoleResp, error)
	// 更新角色
	UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error)
	// 删除角色
	DeletesRole(context.Context, *DeletesRoleReq) (*DeletesRoleResp, error)
	// 查询角色列表
	FindRoleList(context.Context, *FindRoleListReq) (*FindRoleListResp, error)
	// 查询所有角色
	FindAllRole(context.Context, *FindAllRoleReq) (*FindAllRoleResp, error)
	// 更新角色菜单
	UpdateRoleMenus(context.Context, *UpdateRoleMenusReq) (*UpdateRoleMenusResp, error)
	// 更新角色资源
	UpdateRoleApis(context.Context, *UpdateRoleApisReq) (*UpdateRoleApisResp, error)
	// 查询角色资源权限
	FindRoleResources(context.Context, *FindRoleResourcesReq) (*FindRoleResourcesResp, error)
	// 修改用户角色
	UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error)
	// 获取用户接口权限
	FindUserApis(context.Context, *FindUserApisReq) (*FindUserApisResp, error)
	// 获取用户菜单权限
	FindUserMenus(context.Context, *FindUserMenusReq) (*FindUserMenusResp, error)
	// 获取用户角色信息
	FindUserRoles(context.Context, *FindUserRolesReq) (*FindUserRolesResp, error)
	mustEmbedUnimplementedPermissionRpcServer()
}

// UnimplementedPermissionRpcServer must be embedded to have forward compatible implementations.
type UnimplementedPermissionRpcServer struct {
}

func (UnimplementedPermissionRpcServer) AddApi(context.Context, *AddApiReq) (*AddApiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddApi not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedPermissionRpcServer) DeletesApi(context.Context, *DeletesApiReq) (*DeletesApiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesApi not implemented")
}
func (UnimplementedPermissionRpcServer) FindApiList(context.Context, *FindApiListReq) (*FindApiListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindApiList not implemented")
}
func (UnimplementedPermissionRpcServer) SyncApiList(context.Context, *SyncApiListReq) (*SyncApiListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncApiList not implemented")
}
func (UnimplementedPermissionRpcServer) CleanApiList(context.Context, *CleanApiListReq) (*CleanApiListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanApiList not implemented")
}
func (UnimplementedPermissionRpcServer) FindAllApi(context.Context, *FindAllApiReq) (*FindAllApiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllApi not implemented")
}
func (UnimplementedPermissionRpcServer) AddMenu(context.Context, *AddMenuReq) (*AddMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMenu not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateMenu(context.Context, *UpdateMenuReq) (*UpdateMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenu not implemented")
}
func (UnimplementedPermissionRpcServer) DeletesMenu(context.Context, *DeletesMenuReq) (*DeletesMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesMenu not implemented")
}
func (UnimplementedPermissionRpcServer) FindMenuList(context.Context, *FindMenuListReq) (*FindMenuListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMenuList not implemented")
}
func (UnimplementedPermissionRpcServer) SyncMenuList(context.Context, *SyncMenuListReq) (*SyncMenuListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMenuList not implemented")
}
func (UnimplementedPermissionRpcServer) CleanMenuList(context.Context, *CleanMenuListReq) (*CleanMenuListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanMenuList not implemented")
}
func (UnimplementedPermissionRpcServer) FindAllMenu(context.Context, *FindAllMenuReq) (*FindAllMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllMenu not implemented")
}
func (UnimplementedPermissionRpcServer) AddRole(context.Context, *AddRoleReq) (*AddRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedPermissionRpcServer) DeletesRole(context.Context, *DeletesRoleReq) (*DeletesRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesRole not implemented")
}
func (UnimplementedPermissionRpcServer) FindRoleList(context.Context, *FindRoleListReq) (*FindRoleListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRoleList not implemented")
}
func (UnimplementedPermissionRpcServer) FindAllRole(context.Context, *FindAllRoleReq) (*FindAllRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllRole not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateRoleMenus(context.Context, *UpdateRoleMenusReq) (*UpdateRoleMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleMenus not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateRoleApis(context.Context, *UpdateRoleApisReq) (*UpdateRoleApisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleApis not implemented")
}
func (UnimplementedPermissionRpcServer) FindRoleResources(context.Context, *FindRoleResourcesReq) (*FindRoleResourcesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRoleResources not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedPermissionRpcServer) FindUserApis(context.Context, *FindUserApisReq) (*FindUserApisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserApis not implemented")
}
func (UnimplementedPermissionRpcServer) FindUserMenus(context.Context, *FindUserMenusReq) (*FindUserMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserMenus not implemented")
}
func (UnimplementedPermissionRpcServer) FindUserRoles(context.Context, *FindUserRolesReq) (*FindUserRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserRoles not implemented")
}
func (UnimplementedPermissionRpcServer) mustEmbedUnimplementedPermissionRpcServer() {}

// UnsafePermissionRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionRpcServer will
// result in compilation errors.
type UnsafePermissionRpcServer interface {
	mustEmbedUnimplementedPermissionRpcServer()
}

func RegisterPermissionRpcServer(s grpc.ServiceRegistrar, srv PermissionRpcServer) {
	s.RegisterService(&PermissionRpc_ServiceDesc, srv)
}

func _PermissionRpc_AddApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).AddApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_AddApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).AddApi(ctx, req.(*AddApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateApi(ctx, req.(*UpdateApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_DeletesApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).DeletesApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_DeletesApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).DeletesApi(ctx, req.(*DeletesApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindApiList(ctx, req.(*FindApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_SyncApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).SyncApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_SyncApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).SyncApiList(ctx, req.(*SyncApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_CleanApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).CleanApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_CleanApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).CleanApiList(ctx, req.(*CleanApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindAllApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindAllApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindAllApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindAllApi(ctx, req.(*FindAllApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_AddMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).AddMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_AddMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).AddMenu(ctx, req.(*AddMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateMenu(ctx, req.(*UpdateMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_DeletesMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).DeletesMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_DeletesMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).DeletesMenu(ctx, req.(*DeletesMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMenuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindMenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindMenuList(ctx, req.(*FindMenuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_SyncMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMenuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).SyncMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_SyncMenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).SyncMenuList(ctx, req.(*SyncMenuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_CleanMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanMenuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).CleanMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_CleanMenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).CleanMenuList(ctx, req.(*CleanMenuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindAllMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindAllMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindAllMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindAllMenu(ctx, req.(*FindAllMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).AddRole(ctx, req.(*AddRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_DeletesRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).DeletesRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_DeletesRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).DeletesRole(ctx, req.(*DeletesRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindRoleList(ctx, req.(*FindRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindAllRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindAllRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindAllRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindAllRole(ctx, req.(*FindAllRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateRoleMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateRoleMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateRoleMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateRoleMenus(ctx, req.(*UpdateRoleMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateRoleApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleApisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateRoleApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateRoleApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateRoleApis(ctx, req.(*UpdateRoleApisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindRoleResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRoleResourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindRoleResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindRoleResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindRoleResources(ctx, req.(*FindRoleResourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateUserRole(ctx, req.(*UpdateUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindUserApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserApisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindUserApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindUserApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindUserApis(ctx, req.(*FindUserApisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindUserMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindUserMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindUserMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindUserMenus(ctx, req.(*FindUserMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindUserRoles(ctx, req.(*FindUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionRpc_ServiceDesc is the grpc.ServiceDesc for PermissionRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permissionrpc.PermissionRpc",
	HandlerType: (*PermissionRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddApi",
			Handler:    _PermissionRpc_AddApi_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _PermissionRpc_UpdateApi_Handler,
		},
		{
			MethodName: "DeletesApi",
			Handler:    _PermissionRpc_DeletesApi_Handler,
		},
		{
			MethodName: "FindApiList",
			Handler:    _PermissionRpc_FindApiList_Handler,
		},
		{
			MethodName: "SyncApiList",
			Handler:    _PermissionRpc_SyncApiList_Handler,
		},
		{
			MethodName: "CleanApiList",
			Handler:    _PermissionRpc_CleanApiList_Handler,
		},
		{
			MethodName: "FindAllApi",
			Handler:    _PermissionRpc_FindAllApi_Handler,
		},
		{
			MethodName: "AddMenu",
			Handler:    _PermissionRpc_AddMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _PermissionRpc_UpdateMenu_Handler,
		},
		{
			MethodName: "DeletesMenu",
			Handler:    _PermissionRpc_DeletesMenu_Handler,
		},
		{
			MethodName: "FindMenuList",
			Handler:    _PermissionRpc_FindMenuList_Handler,
		},
		{
			MethodName: "SyncMenuList",
			Handler:    _PermissionRpc_SyncMenuList_Handler,
		},
		{
			MethodName: "CleanMenuList",
			Handler:    _PermissionRpc_CleanMenuList_Handler,
		},
		{
			MethodName: "FindAllMenu",
			Handler:    _PermissionRpc_FindAllMenu_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _PermissionRpc_AddRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _PermissionRpc_UpdateRole_Handler,
		},
		{
			MethodName: "DeletesRole",
			Handler:    _PermissionRpc_DeletesRole_Handler,
		},
		{
			MethodName: "FindRoleList",
			Handler:    _PermissionRpc_FindRoleList_Handler,
		},
		{
			MethodName: "FindAllRole",
			Handler:    _PermissionRpc_FindAllRole_Handler,
		},
		{
			MethodName: "UpdateRoleMenus",
			Handler:    _PermissionRpc_UpdateRoleMenus_Handler,
		},
		{
			MethodName: "UpdateRoleApis",
			Handler:    _PermissionRpc_UpdateRoleApis_Handler,
		},
		{
			MethodName: "FindRoleResources",
			Handler:    _PermissionRpc_FindRoleResources_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _PermissionRpc_UpdateUserRole_Handler,
		},
		{
			MethodName: "FindUserApis",
			Handler:    _PermissionRpc_FindUserApis_Handler,
		},
		{
			MethodName: "FindUserMenus",
			Handler:    _PermissionRpc_FindUserMenus_Handler,
		},
		{
			MethodName: "FindUserRoles",
			Handler:    _PermissionRpc_FindUserRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}
