// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: guest.proto

package guestservice

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"

	"github.com/ve-weiyi/ve-blog-golang/service/app/rpc/internal/pb/guestrpc"
)

type (
	GetGuestRequest    = guestrpc.GetGuestRequest
	GetGuestResponse   = guestrpc.GetGuestResponse
	Guest              = guestrpc.Guest
	ListGuestsRequest  = guestrpc.ListGuestsRequest
	ListGuestsResponse = guestrpc.ListGuestsResponse
	PageQuery          = guestrpc.PageQuery
	PageResult         = guestrpc.PageResult

	GuestService interface {
		// 分页查询游客信息列表
		ListGuests(ctx context.Context, in *ListGuestsRequest, opts ...grpc.CallOption) (*ListGuestsResponse, error)
		// 获取游客环境信息
		GetGuest(ctx context.Context, in *GetGuestRequest, opts ...grpc.CallOption) (*GetGuestResponse, error)
	}

	defaultGuestService struct {
		cli zrpc.Client
	}
)

func NewGuestService(cli zrpc.Client) GuestService {
	return &defaultGuestService{
		cli: cli,
	}
}

// 分页查询游客信息列表
func (m *defaultGuestService) ListGuests(ctx context.Context, in *ListGuestsRequest, opts ...grpc.CallOption) (*ListGuestsResponse, error) {
	client := guestrpc.NewGuestServiceClient(m.cli.Conn())
	return client.ListGuests(ctx, in, opts...)
}

// 获取游客环境信息
func (m *defaultGuestService) GetGuest(ctx context.Context, in *GetGuestRequest, opts ...grpc.CallOption) (*GetGuestResponse, error) {
	client := guestrpc.NewGuestServiceClient(m.cli.Conn())
	return client.GetGuest(ctx, in, opts...)
}
