system:
  version: 1.0.0
  env: develop
  addr: 9999
  router-prefix: "api/v1"
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  runtime-path: runtime/

mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: blog-v2
  username: root
  password: mysql7914
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: info
  log-zap: false

redis:
  db: 3
  host: 127.0.0.1
  port: "6379"
  password: redis7914

# mq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

email:
  host: smtp.qq.com
  port: 465
  # 邮箱 647166282@qq.com
  username: 647166282@qq.com
  # 16位授权码 不是邮箱密码
  password: culyqmzvmppabccd
  # 抄送邮箱,逗号隔开
  deliver: 791422171@qq.com
  is-ssl: true
  nickname: 与梦

jwt:
  signing-key: github.com/ve-weiyi/ve-blog-golang/server
  expires-time: 7d
  buffer-time: 1d
  issuer: blog

zap:
  level: info
  prefix: ''
  format: console
  director: runtime/logs
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

oauth:
  qq:
    client-id: 101993700
    client-secret: 1c0a86a1760a8bf81176940bd513c16b
    redirect-url: https://www.ve77.cn/blog/oauth/login/qq

  feishu:
    client-id: cli_a4105d6dbc38900e
    client-secret: BZtobcwHK6c3sDyack9DDgQru6fgwUJF
    redirect-url: http://127.0.0.1:8888/blog/oauth/login/feishu

  weibo:
    client-id: 2658270041
    client-secret: 29a13e1454d7bff1c2a255185454bb86
    redirect-url: https://ve77.cn/blog/oauth/login/weibo

captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

# 文件上传
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip +端口
    bucket-url: http://localhost:9999
    # 本地文件存储路径，不加/则为当前目录下
    base-path: runtime/uploads

  # aliyun oss configuration
  aliyun:
    zone:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t7vTeWDKrYUQFkVto8a
    access-key-secret: GGSaxLp2aCFpQq7sgGOf9TnLxHeECu
    bucket-name: ve-blog
    bucket-url: http://ve-blog.oss-cn-shenzhen.aliyuncs.com
    base-path: blog
  # aliyun oss configuration

  qiniu:
    zone: ZoneHuaDong
    endpoint: rxb1y0x1n.hn-bkt.clouddn.com
    access-key-id: gyoAZPHHZrwXt4HhG7SNRaxRShJPhEKvxJJKhDUV
    access-key-secret: OqbepkdXNm0pKfZMy1ziPqdYjZMCtdzRIrz1Hlhi
    bucket-name: blog-port
    bucket-url: http://rxb1y0x1n.hn-bkt.clouddn.com
    base-path: blog
