# system configuration
system:
  version: 1.0.0
  env: develop
  port: 9999
  router-prefix: "api/v1"
  use-multipoint: false
  runtime-path: runtime/

# jwt token configuration
jwt:
  signing-key: veweiyi.cn
  expires-time: 7d
  issuer: blog
  type: Bearer

# zap logger configuration
zap:
  mode: console # 模式 console or file
  format: console # 格式化 json or console
  level: info # 等级 debug info warn error dpanic panic fatal
  prefix: '' # 前缀 logger prefix
  encode-caller: long # 显示调用信息 short or long
  encode-colorful: true # 彩色显示
  filename: blog.log
  cache-dir: runtime/logs # 缓存目录 log file dir
  max-age: 0

# mysql connect configuration
mysql:
  host: 127.0.0.1
  port: "3306"
  username: root
  password: mysql7914
  dbname: blog-veweiyi
  config: charset=utf8mb4&parseTime=True&loc=Local

# redis configuration
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 3

# mq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

# email configuration
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效

# 第三方登录
oauth:
  qq:
    client-id: xxx
    client-secret: xxx
    redirect-uri: xxx

  feishu:
    client-id: xxx
    client-secret: xxx
    redirect-uri: xxx

  weibo:
    client-id: xxx
    client-secret: xxx
    redirect-uri: xxx

# 文件上传
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip +端口
    url: http://localhost:9999
    # 本地文件存储路径，不加/则为当前目录下
    path: runtime/uploads/file

  # aliyun oss configuration
  aliyun:
    zone:
    endpoint: oss-cn-xxxx.aliyuncs.com
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: xxxx
    bucket-url: xxxx
    base-path: xxxx

  # qiniu oss configuration
  qiniu:
    zone: ZoneHuaDong # 地区
    endpoint: xxx.hn-bkt.clouddn.com  # 访问域名
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: xxxx # 存储空间名称
    bucket-url: xxxx # 上传文件的访问域名 例如: http://xxx.hn-bkt.clouddn.com
    base-path: /uploads  # 文件存储在bucket下的路径




