# system configuration
system:
  env: develop # 运行环境 可选值: develop、test、production
  addr: 9999   # 项目端口
  db-type: mysql
  oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-redis: false # 使用redis
  use-multipoint: false # 使用多点登录
  #项目运行时生成的目录
  runtime-path: runtime/
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# jwt token configuration
jwt:
  signing-key: blog
  expires-time: 7d
  issuer: blog
  type: Bearer

# zap logger configuration
zap:
  server-name: blog
  mode: console # 模式 console or file
  format: console # 格式化 json or console
  level: info # 等级 debug info warn error dpanic panic fatal
  prefix: '' # 前缀 logger prefix
  encode-level: LowercaseLevelEncoder
  encode-caller: long # 显示调用信息 short or long
  encode-colorful: true # 彩色显示
  cache-dir: runtime/logs # 缓存目录 log file dir
  max-age: 0

# redis configuration
redis:
  db: 3
  host: 127.0.0.1
  port: 6379
  password: ""

# mysql connect configuration
mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: blog-plus
  username: root
  password: mysql7914
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false

db-list:
  - disable: true # 是否禁用
    type: "" # 数据库的类型,目前支持mysql、pgsql、mssql、oracle
    alias-name: "" # 数据库的名称,注意: alias-name 需要在db-list中唯一
    host: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效

# email configuration
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test

# 文件上传
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip +端口
    url: http://localhost:9999
    # 本地文件存储路径，不加/则为当前目录下
    path: runtime/uploads/file

  # aliyun oss configuration
  aliyun:
    zone:
    endpoint: oss-cn-xxxx.aliyuncs.com
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: xxxx
    bucket-url: xxxx
    base-path: xxxx

  # qiniu oss configuration
  qiniu:
    zone: ZoneHuaDong # 地区
    endpoint: xxx.hn-bkt.clouddn.com  # 访问域名
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: xxxx # 存储空间名称
    bucket-url: xxxx # 上传文件的访问域名 例如: http://xxx.hn-bkt.clouddn.com
    base-path: /uploads  # 文件存储在bucket下的路径




