// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: syslog.proto

// proto 包名

package syslogrpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SyslogService_ListLoginLogs_FullMethodName      = "/syslogrpc.SyslogService/ListLoginLogs"
	SyslogService_CreateLoginLog_FullMethodName     = "/syslogrpc.SyslogService/CreateLoginLog"
	SyslogService_UpdateLoginLog_FullMethodName     = "/syslogrpc.SyslogService/UpdateLoginLog"
	SyslogService_DeleteLoginLog_FullMethodName     = "/syslogrpc.SyslogService/DeleteLoginLog"
	SyslogService_ListOperationLogs_FullMethodName  = "/syslogrpc.SyslogService/ListOperationLogs"
	SyslogService_CreateOperationLog_FullMethodName = "/syslogrpc.SyslogService/CreateOperationLog"
	SyslogService_DeleteOperationLog_FullMethodName = "/syslogrpc.SyslogService/DeleteOperationLog"
	SyslogService_ListUploadLogs_FullMethodName     = "/syslogrpc.SyslogService/ListUploadLogs"
	SyslogService_CreateUploadLog_FullMethodName    = "/syslogrpc.SyslogService/CreateUploadLog"
	SyslogService_DeleteUploadLog_FullMethodName    = "/syslogrpc.SyslogService/DeleteUploadLog"
	SyslogService_ListVisitLogs_FullMethodName      = "/syslogrpc.SyslogService/ListVisitLogs"
	SyslogService_CreateVisitLog_FullMethodName     = "/syslogrpc.SyslogService/CreateVisitLog"
	SyslogService_DeleteVisitLog_FullMethodName     = "/syslogrpc.SyslogService/DeleteVisitLog"
)

// SyslogServiceClient is the client API for SyslogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyslogServiceClient interface {
	// 分页查询用户登录日志
	ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error)
	// 创建用户登录日志
	CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error)
	// 更新登出时间
	UpdateLoginLog(ctx context.Context, in *UpdateLoginLogRequest, opts ...grpc.CallOption) (*UpdateLoginLogResponse, error)
	// 批量删除用户登录日志
	DeleteLoginLog(ctx context.Context, in *DeleteLoginLogRequest, opts ...grpc.CallOption) (*DeleteLoginLogResponse, error)
	// 分页查询操作日志
	ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error)
	// 创建操作日志
	CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error)
	// 批量删除操作日志
	DeleteOperationLog(ctx context.Context, in *DeleteOperationLogRequest, opts ...grpc.CallOption) (*DeleteOperationLogResponse, error)
	// 分页查询文件上传日志
	ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error)
	// 创建文件上传日志
	CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error)
	// 批量删除文件上传日志
	DeleteUploadLog(ctx context.Context, in *DeleteUploadLogRequest, opts ...grpc.CallOption) (*DeleteUploadLogResponse, error)
	// 分页查询访问日志
	ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error)
	// 创建访问日志
	CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error)
	// 批量删除访问日志
	DeleteVisitLog(ctx context.Context, in *DeleteVisitLogRequest, opts ...grpc.CallOption) (*DeleteVisitLogResponse, error)
}

type syslogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyslogServiceClient(cc grpc.ClientConnInterface) SyslogServiceClient {
	return &syslogServiceClient{cc}
}

func (c *syslogServiceClient) ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error) {
	out := new(ListLoginLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListLoginLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error) {
	out := new(CreateLoginLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateLoginLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) UpdateLoginLog(ctx context.Context, in *UpdateLoginLogRequest, opts ...grpc.CallOption) (*UpdateLoginLogResponse, error) {
	out := new(UpdateLoginLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_UpdateLoginLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) DeleteLoginLog(ctx context.Context, in *DeleteLoginLogRequest, opts ...grpc.CallOption) (*DeleteLoginLogResponse, error) {
	out := new(DeleteLoginLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_DeleteLoginLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error) {
	out := new(ListOperationLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListOperationLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error) {
	out := new(CreateOperationLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateOperationLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) DeleteOperationLog(ctx context.Context, in *DeleteOperationLogRequest, opts ...grpc.CallOption) (*DeleteOperationLogResponse, error) {
	out := new(DeleteOperationLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_DeleteOperationLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error) {
	out := new(ListUploadLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListUploadLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error) {
	out := new(CreateUploadLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateUploadLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) DeleteUploadLog(ctx context.Context, in *DeleteUploadLogRequest, opts ...grpc.CallOption) (*DeleteUploadLogResponse, error) {
	out := new(DeleteUploadLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_DeleteUploadLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error) {
	out := new(ListVisitLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListVisitLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error) {
	out := new(CreateVisitLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateVisitLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) DeleteVisitLog(ctx context.Context, in *DeleteVisitLogRequest, opts ...grpc.CallOption) (*DeleteVisitLogResponse, error) {
	out := new(DeleteVisitLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_DeleteVisitLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyslogServiceServer is the server API for SyslogService service.
// All implementations must embed UnimplementedSyslogServiceServer
// for forward compatibility
type SyslogServiceServer interface {
	// 分页查询用户登录日志
	ListLoginLogs(context.Context, *ListLoginLogsRequest) (*ListLoginLogsResponse, error)
	// 创建用户登录日志
	CreateLoginLog(context.Context, *CreateLoginLogRequest) (*CreateLoginLogResponse, error)
	// 更新登出时间
	UpdateLoginLog(context.Context, *UpdateLoginLogRequest) (*UpdateLoginLogResponse, error)
	// 批量删除用户登录日志
	DeleteLoginLog(context.Context, *DeleteLoginLogRequest) (*DeleteLoginLogResponse, error)
	// 分页查询操作日志
	ListOperationLogs(context.Context, *ListOperationLogsRequest) (*ListOperationLogsResponse, error)
	// 创建操作日志
	CreateOperationLog(context.Context, *CreateOperationLogRequest) (*CreateOperationLogResponse, error)
	// 批量删除操作日志
	DeleteOperationLog(context.Context, *DeleteOperationLogRequest) (*DeleteOperationLogResponse, error)
	// 分页查询文件上传日志
	ListUploadLogs(context.Context, *ListUploadLogsRequest) (*ListUploadLogsResponse, error)
	// 创建文件上传日志
	CreateUploadLog(context.Context, *CreateUploadLogRequest) (*CreateUploadLogResponse, error)
	// 批量删除文件上传日志
	DeleteUploadLog(context.Context, *DeleteUploadLogRequest) (*DeleteUploadLogResponse, error)
	// 分页查询访问日志
	ListVisitLogs(context.Context, *ListVisitLogsRequest) (*ListVisitLogsResponse, error)
	// 创建访问日志
	CreateVisitLog(context.Context, *CreateVisitLogRequest) (*CreateVisitLogResponse, error)
	// 批量删除访问日志
	DeleteVisitLog(context.Context, *DeleteVisitLogRequest) (*DeleteVisitLogResponse, error)
	mustEmbedUnimplementedSyslogServiceServer()
}

// UnimplementedSyslogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyslogServiceServer struct {
}

func (UnimplementedSyslogServiceServer) ListLoginLogs(context.Context, *ListLoginLogsRequest) (*ListLoginLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLoginLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateLoginLog(context.Context, *CreateLoginLogRequest) (*CreateLoginLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoginLog not implemented")
}
func (UnimplementedSyslogServiceServer) UpdateLoginLog(context.Context, *UpdateLoginLogRequest) (*UpdateLoginLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoginLog not implemented")
}
func (UnimplementedSyslogServiceServer) DeleteLoginLog(context.Context, *DeleteLoginLogRequest) (*DeleteLoginLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLoginLog not implemented")
}
func (UnimplementedSyslogServiceServer) ListOperationLogs(context.Context, *ListOperationLogsRequest) (*ListOperationLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperationLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateOperationLog(context.Context, *CreateOperationLogRequest) (*CreateOperationLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOperationLog not implemented")
}
func (UnimplementedSyslogServiceServer) DeleteOperationLog(context.Context, *DeleteOperationLogRequest) (*DeleteOperationLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOperationLog not implemented")
}
func (UnimplementedSyslogServiceServer) ListUploadLogs(context.Context, *ListUploadLogsRequest) (*ListUploadLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUploadLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateUploadLog(context.Context, *CreateUploadLogRequest) (*CreateUploadLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUploadLog not implemented")
}
func (UnimplementedSyslogServiceServer) DeleteUploadLog(context.Context, *DeleteUploadLogRequest) (*DeleteUploadLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUploadLog not implemented")
}
func (UnimplementedSyslogServiceServer) ListVisitLogs(context.Context, *ListVisitLogsRequest) (*ListVisitLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVisitLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateVisitLog(context.Context, *CreateVisitLogRequest) (*CreateVisitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVisitLog not implemented")
}
func (UnimplementedSyslogServiceServer) DeleteVisitLog(context.Context, *DeleteVisitLogRequest) (*DeleteVisitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVisitLog not implemented")
}
func (UnimplementedSyslogServiceServer) mustEmbedUnimplementedSyslogServiceServer() {}

// UnsafeSyslogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyslogServiceServer will
// result in compilation errors.
type UnsafeSyslogServiceServer interface {
	mustEmbedUnimplementedSyslogServiceServer()
}

func RegisterSyslogServiceServer(s grpc.ServiceRegistrar, srv SyslogServiceServer) {
	s.RegisterService(&SyslogService_ServiceDesc, srv)
}

func _SyslogService_ListLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoginLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListLoginLogs(ctx, req.(*ListLoginLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateLoginLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateLoginLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateLoginLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateLoginLog(ctx, req.(*CreateLoginLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_UpdateLoginLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoginLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).UpdateLoginLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_UpdateLoginLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).UpdateLoginLog(ctx, req.(*UpdateLoginLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_DeleteLoginLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoginLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).DeleteLoginLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_DeleteLoginLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).DeleteLoginLog(ctx, req.(*DeleteLoginLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListOperationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListOperationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListOperationLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListOperationLogs(ctx, req.(*ListOperationLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateOperationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateOperationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateOperationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateOperationLog(ctx, req.(*CreateOperationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_DeleteOperationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).DeleteOperationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_DeleteOperationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).DeleteOperationLog(ctx, req.(*DeleteOperationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListUploadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUploadLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListUploadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListUploadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListUploadLogs(ctx, req.(*ListUploadLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateUploadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateUploadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateUploadLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateUploadLog(ctx, req.(*CreateUploadLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_DeleteUploadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUploadLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).DeleteUploadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_DeleteUploadLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).DeleteUploadLog(ctx, req.(*DeleteUploadLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListVisitLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVisitLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListVisitLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListVisitLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListVisitLogs(ctx, req.(*ListVisitLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateVisitLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVisitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateVisitLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateVisitLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateVisitLog(ctx, req.(*CreateVisitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_DeleteVisitLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVisitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).DeleteVisitLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_DeleteVisitLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).DeleteVisitLog(ctx, req.(*DeleteVisitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyslogService_ServiceDesc is the grpc.ServiceDesc for SyslogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyslogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syslogrpc.SyslogService",
	HandlerType: (*SyslogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLoginLogs",
			Handler:    _SyslogService_ListLoginLogs_Handler,
		},
		{
			MethodName: "CreateLoginLog",
			Handler:    _SyslogService_CreateLoginLog_Handler,
		},
		{
			MethodName: "UpdateLoginLog",
			Handler:    _SyslogService_UpdateLoginLog_Handler,
		},
		{
			MethodName: "DeleteLoginLog",
			Handler:    _SyslogService_DeleteLoginLog_Handler,
		},
		{
			MethodName: "ListOperationLogs",
			Handler:    _SyslogService_ListOperationLogs_Handler,
		},
		{
			MethodName: "CreateOperationLog",
			Handler:    _SyslogService_CreateOperationLog_Handler,
		},
		{
			MethodName: "DeleteOperationLog",
			Handler:    _SyslogService_DeleteOperationLog_Handler,
		},
		{
			MethodName: "ListUploadLogs",
			Handler:    _SyslogService_ListUploadLogs_Handler,
		},
		{
			MethodName: "CreateUploadLog",
			Handler:    _SyslogService_CreateUploadLog_Handler,
		},
		{
			MethodName: "DeleteUploadLog",
			Handler:    _SyslogService_DeleteUploadLog_Handler,
		},
		{
			MethodName: "ListVisitLogs",
			Handler:    _SyslogService_ListVisitLogs_Handler,
		},
		{
			MethodName: "CreateVisitLog",
			Handler:    _SyslogService_CreateVisitLog_Handler,
		},
		{
			MethodName: "DeleteVisitLog",
			Handler:    _SyslogService_DeleteVisitLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syslog.proto",
}
