// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: syslog.proto

package syslogrpc

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/blog-gozero/service/rpc/blog/internal/pb/syslogrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddLogoutLogReq          = syslogrpc.AddLogoutLogReq
	AddLogoutLogResp         = syslogrpc.AddLogoutLogResp
	BatchResp                = syslogrpc.BatchResp
	CountResp                = syslogrpc.CountResp
	EmptyReq                 = syslogrpc.EmptyReq
	EmptyResp                = syslogrpc.EmptyResp
	FindLoginLogListReq      = syslogrpc.FindLoginLogListReq
	FindLoginLogListResp     = syslogrpc.FindLoginLogListResp
	FindOperationLogListReq  = syslogrpc.FindOperationLogListReq
	FindOperationLogListResp = syslogrpc.FindOperationLogListResp
	FindUploadLogListReq     = syslogrpc.FindUploadLogListReq
	FindUploadLogListResp    = syslogrpc.FindUploadLogListResp
	FindVisitLogListReq      = syslogrpc.FindVisitLogListReq
	FindVisitLogListResp     = syslogrpc.FindVisitLogListResp
	IdReq                    = syslogrpc.IdReq
	IdsReq                   = syslogrpc.IdsReq
	LoginLogDetails          = syslogrpc.LoginLogDetails
	LoginLogNewReq           = syslogrpc.LoginLogNewReq
	OperationLogDetails      = syslogrpc.OperationLogDetails
	OperationLogNewReq       = syslogrpc.OperationLogNewReq
	UploadLogDetails         = syslogrpc.UploadLogDetails
	UploadLogNewReq          = syslogrpc.UploadLogNewReq
	UserIdReq                = syslogrpc.UserIdReq
	VisitLogDetails          = syslogrpc.VisitLogDetails
	VisitLogNewReq           = syslogrpc.VisitLogNewReq

	SyslogRpc interface {
		// 创建登录记录
		AddLoginLog(ctx context.Context, in *LoginLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 更新登录记录
		AddLogoutLog(ctx context.Context, in *AddLogoutLogReq, opts ...grpc.CallOption) (*AddLogoutLogResp, error)
		// 批量删除登录记录
		DeletesLoginLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询登录记录列表
		FindLoginLogList(ctx context.Context, in *FindLoginLogListReq, opts ...grpc.CallOption) (*FindLoginLogListResp, error)
		// 创建访问记录
		AddVisitLog(ctx context.Context, in *VisitLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 批量删除访问记录
		DeletesVisitLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询操作访问列表
		FindVisitLogList(ctx context.Context, in *FindVisitLogListReq, opts ...grpc.CallOption) (*FindVisitLogListResp, error)
		// 创建操作记录
		AddOperationLog(ctx context.Context, in *OperationLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 批量删除操作记录
		DeletesOperationLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询操作记录列表
		FindOperationLogList(ctx context.Context, in *FindOperationLogListReq, opts ...grpc.CallOption) (*FindOperationLogListResp, error)
		// 创建上传记录
		AddUploadLog(ctx context.Context, in *UploadLogNewReq, opts ...grpc.CallOption) (*UploadLogDetails, error)
		// 批量删除上传记录
		DeletesUploadLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询上传记录列表
		FindUploadLogList(ctx context.Context, in *FindUploadLogListReq, opts ...grpc.CallOption) (*FindUploadLogListResp, error)
	}

	defaultSyslogRpc struct {
		cli zrpc.Client
	}
)

func NewSyslogRpc(cli zrpc.Client) SyslogRpc {
	return &defaultSyslogRpc{
		cli: cli,
	}
}

// 创建登录记录
func (m *defaultSyslogRpc) AddLoginLog(ctx context.Context, in *LoginLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.AddLoginLog(ctx, in, opts...)
}

// 更新登录记录
func (m *defaultSyslogRpc) AddLogoutLog(ctx context.Context, in *AddLogoutLogReq, opts ...grpc.CallOption) (*AddLogoutLogResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.AddLogoutLog(ctx, in, opts...)
}

// 批量删除登录记录
func (m *defaultSyslogRpc) DeletesLoginLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.DeletesLoginLog(ctx, in, opts...)
}

// 查询登录记录列表
func (m *defaultSyslogRpc) FindLoginLogList(ctx context.Context, in *FindLoginLogListReq, opts ...grpc.CallOption) (*FindLoginLogListResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.FindLoginLogList(ctx, in, opts...)
}

// 创建访问记录
func (m *defaultSyslogRpc) AddVisitLog(ctx context.Context, in *VisitLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.AddVisitLog(ctx, in, opts...)
}

// 批量删除访问记录
func (m *defaultSyslogRpc) DeletesVisitLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.DeletesVisitLog(ctx, in, opts...)
}

// 查询操作访问列表
func (m *defaultSyslogRpc) FindVisitLogList(ctx context.Context, in *FindVisitLogListReq, opts ...grpc.CallOption) (*FindVisitLogListResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.FindVisitLogList(ctx, in, opts...)
}

// 创建操作记录
func (m *defaultSyslogRpc) AddOperationLog(ctx context.Context, in *OperationLogNewReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.AddOperationLog(ctx, in, opts...)
}

// 批量删除操作记录
func (m *defaultSyslogRpc) DeletesOperationLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.DeletesOperationLog(ctx, in, opts...)
}

// 查询操作记录列表
func (m *defaultSyslogRpc) FindOperationLogList(ctx context.Context, in *FindOperationLogListReq, opts ...grpc.CallOption) (*FindOperationLogListResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.FindOperationLogList(ctx, in, opts...)
}

// 创建上传记录
func (m *defaultSyslogRpc) AddUploadLog(ctx context.Context, in *UploadLogNewReq, opts ...grpc.CallOption) (*UploadLogDetails, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.AddUploadLog(ctx, in, opts...)
}

// 批量删除上传记录
func (m *defaultSyslogRpc) DeletesUploadLog(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.DeletesUploadLog(ctx, in, opts...)
}

// 查询上传记录列表
func (m *defaultSyslogRpc) FindUploadLogList(ctx context.Context, in *FindUploadLogListReq, opts ...grpc.CallOption) (*FindUploadLogListResp, error) {
	client := syslogrpc.NewSyslogRpcClient(m.cli.Conn())
	return client.FindUploadLogList(ctx, in, opts...)
}
