// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package rolerpc

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/rpc/blog/internal/pb/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalysisArticleResp       = blog.AnalysisArticleResp
	Api                       = blog.Api
	ApiDetails                = blog.ApiDetails
	ArticleCategory           = blog.ArticleCategory
	ArticleDetails            = blog.ArticleDetails
	ArticleNew                = blog.ArticleNew
	ArticleTag                = blog.ArticleTag
	BatchResp                 = blog.BatchResp
	BindUserEmailReq          = blog.BindUserEmailReq
	CategoryDetails           = blog.CategoryDetails
	CategoryNew               = blog.CategoryNew
	ChatRecord                = blog.ChatRecord
	Comment                   = blog.Comment
	CommentUserInfo           = blog.CommentUserInfo
	CountResp                 = blog.CountResp
	EmptyReq                  = blog.EmptyReq
	EmptyResp                 = blog.EmptyResp
	FindApiListResp           = blog.FindApiListResp
	FindArticleListReq        = blog.FindArticleListReq
	FindArticleListResp       = blog.FindArticleListResp
	FindArticlesByCategoryReq = blog.FindArticlesByCategoryReq
	FindArticlesByTagReq      = blog.FindArticlesByTagReq
	FindCategoryListReq       = blog.FindCategoryListReq
	FindCategoryListResp      = blog.FindCategoryListResp
	FindChatRecordListResp    = blog.FindChatRecordListResp
	FindCommentListResp       = blog.FindCommentListResp
	FindConfigReq             = blog.FindConfigReq
	FindConfigResp            = blog.FindConfigResp
	FindFriendLinkListResp    = blog.FindFriendLinkListResp
	FindLikeArticleResp       = blog.FindLikeArticleResp
	FindLikeCommentResp       = blog.FindLikeCommentResp
	FindLikeTalkResp          = blog.FindLikeTalkResp
	FindLoginHistoryListReq   = blog.FindLoginHistoryListReq
	FindLoginHistoryListResp  = blog.FindLoginHistoryListResp
	FindMenuListResp          = blog.FindMenuListResp
	FindOperationLogListResp  = blog.FindOperationLogListResp
	FindPageListResp          = blog.FindPageListResp
	FindPhotoAlbumListResp    = blog.FindPhotoAlbumListResp
	FindPhotoListResp         = blog.FindPhotoListResp
	FindRemarkListResp        = blog.FindRemarkListResp
	FindRoleListResp          = blog.FindRoleListResp
	FindTagArticleCountReq    = blog.FindTagArticleCountReq
	FindTagByNameReq          = blog.FindTagByNameReq
	FindTagListReq            = blog.FindTagListReq
	FindTagListResp           = blog.FindTagListResp
	FindTalkListResp          = blog.FindTalkListResp
	FindUserListReq           = blog.FindUserListReq
	FindUserListResp          = blog.FindUserListResp
	FindUserRegionListResp    = blog.FindUserRegionListResp
	FriendLink                = blog.FriendLink
	GetLogoutAtReq            = blog.GetLogoutAtReq
	IdReq                     = blog.IdReq
	IdsReq                    = blog.IdsReq
	ListResp                  = blog.ListResp
	LoginReq                  = blog.LoginReq
	LoginResp                 = blog.LoginResp
	LogoffReq                 = blog.LogoffReq
	LogoutReq                 = blog.LogoutReq
	LogoutResp                = blog.LogoutResp
	Menu                      = blog.Menu
	MenuDetails               = blog.MenuDetails
	OauthLoginReq             = blog.OauthLoginReq
	OauthLoginUrlResp         = blog.OauthLoginUrlResp
	OperationLog              = blog.OperationLog
	Page                      = blog.Page
	PageCondition             = blog.PageCondition
	PageLimit                 = blog.PageLimit
	PageQuery                 = blog.PageQuery
	PageSort                  = blog.PageSort
	Photo                     = blog.Photo
	PhotoAlbum                = blog.PhotoAlbum
	RecycleArticleReq         = blog.RecycleArticleReq
	RegisterReq               = blog.RegisterReq
	Remark                    = blog.Remark
	ResetPasswordReq          = blog.ResetPasswordReq
	Role                      = blog.Role
	RoleDetails               = blog.RoleDetails
	RoleResourcesResp         = blog.RoleResourcesResp
	SaveConfigReq             = blog.SaveConfigReq
	SyncMenuReq               = blog.SyncMenuReq
	TagDetails                = blog.TagDetails
	TagMapResp                = blog.TagMapResp
	TagNew                    = blog.TagNew
	Talk                      = blog.Talk
	TalkDetailsDTO            = blog.TalkDetailsDTO
	TopArticleReq             = blog.TopArticleReq
	UpdateRoleApisReq         = blog.UpdateRoleApisReq
	UpdateRoleMenusReq        = blog.UpdateRoleMenusReq
	UpdateUserInfoReq         = blog.UpdateUserInfoReq
	UpdateUserRoleReq         = blog.UpdateUserRoleReq
	UpdateUserStatusReq       = blog.UpdateUserStatusReq
	UploadRecordReq           = blog.UploadRecordReq
	UploadRecordResp          = blog.UploadRecordResp
	UserDetails               = blog.UserDetails
	UserEmailReq              = blog.UserEmailReq
	UserIdReq                 = blog.UserIdReq
	UserInfoResp              = blog.UserInfoResp
	UserLoginHistory          = blog.UserLoginHistory
	UserRegion                = blog.UserRegion
	UserRoleLabel             = blog.UserRoleLabel
	UserVisit                 = blog.UserVisit
	UserVisitPageRsp          = blog.UserVisitPageRsp

	RoleRpc interface {
		// 创建角色
		AddRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
		// 更新角色
		UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
		// 删除角色
		DeleteRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 批量删除角色
		DeleteRoleList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询角色
		FindRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error)
		// 查询角色列表
		FindRoleList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*FindRoleListResp, error)
		// 查询角色资源权限
		FindRoleResources(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleResourcesResp, error)
		// 更新角色菜单
		UpdateRoleMenus(ctx context.Context, in *UpdateRoleMenusReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 更新角色资源
		UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 修改用户角色
		UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 获取用户接口权限
		FindUserApis(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindApiListResp, error)
		// 获取用户菜单权限
		FindUserMenus(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindMenuListResp, error)
		// 获取用户角色信息
		FindUserRoles(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindRoleListResp, error)
	}

	defaultRoleRpc struct {
		cli zrpc.Client
	}
)

func NewRoleRpc(cli zrpc.Client) RoleRpc {
	return &defaultRoleRpc{
		cli: cli,
	}
}

// 创建角色
func (m *defaultRoleRpc) AddRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.AddRole(ctx, in, opts...)
}

// 更新角色
func (m *defaultRoleRpc) UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

// 删除角色
func (m *defaultRoleRpc) DeleteRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// 批量删除角色
func (m *defaultRoleRpc) DeleteRoleList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.DeleteRoleList(ctx, in, opts...)
}

// 查询角色
func (m *defaultRoleRpc) FindRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindRole(ctx, in, opts...)
}

// 查询角色列表
func (m *defaultRoleRpc) FindRoleList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*FindRoleListResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindRoleList(ctx, in, opts...)
}

// 查询角色资源权限
func (m *defaultRoleRpc) FindRoleResources(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleResourcesResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindRoleResources(ctx, in, opts...)
}

// 更新角色菜单
func (m *defaultRoleRpc) UpdateRoleMenus(ctx context.Context, in *UpdateRoleMenusReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.UpdateRoleMenus(ctx, in, opts...)
}

// 更新角色资源
func (m *defaultRoleRpc) UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.UpdateRoleApis(ctx, in, opts...)
}

// 修改用户角色
func (m *defaultRoleRpc) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.UpdateUserRole(ctx, in, opts...)
}

// 获取用户接口权限
func (m *defaultRoleRpc) FindUserApis(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindApiListResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindUserApis(ctx, in, opts...)
}

// 获取用户菜单权限
func (m *defaultRoleRpc) FindUserMenus(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindMenuListResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindUserMenus(ctx, in, opts...)
}

// 获取用户角色信息
func (m *defaultRoleRpc) FindUserRoles(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*FindRoleListResp, error) {
	client := blog.NewRoleRpcClient(m.cli.Conn())
	return client.FindUserRoles(ctx, in, opts...)
}
