version: "3"

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:
  ve-admin-vite:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ve-admin-vite:latest  # 设置新的镜像名称和标签
    container_name: ve-admin-vite
    restart: always
    ports:
      - "7777:80"
