// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package server

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/logic/uploadrpc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/svc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/pb/blog"
)

type UploadRpcServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedUploadRpcServer
}

func NewUploadRpcServer(svcCtx *svc.ServiceContext) *UploadRpcServer {
	return &UploadRpcServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *UploadRpcServer) UploadFile(ctx context.Context, in *blog.UploadRecordReq) (*blog.UploadRecordResp, error) {
	l := uploadrpclogic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

// 上传语言
func (s *UploadRpcServer) UploadVoice(ctx context.Context, in *blog.UploadRecordReq) (*blog.UploadRecordResp, error) {
	l := uploadrpclogic.NewUploadVoiceLogic(ctx, s.svcCtx)
	return l.UploadVoice(in)
}
