// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: news.proto

// proto 包名

package newsrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NewsRpc_AnalysisMessage_FullMethodName        = "/newsrpc.NewsRpc/AnalysisMessage"
	NewsRpc_AddChat_FullMethodName                = "/newsrpc.NewsRpc/AddChat"
	NewsRpc_UpdateChat_FullMethodName             = "/newsrpc.NewsRpc/UpdateChat"
	NewsRpc_GetChat_FullMethodName                = "/newsrpc.NewsRpc/GetChat"
	NewsRpc_DeletesChat_FullMethodName            = "/newsrpc.NewsRpc/DeletesChat"
	NewsRpc_FindChatList_FullMethodName           = "/newsrpc.NewsRpc/FindChatList"
	NewsRpc_AddMessage_FullMethodName             = "/newsrpc.NewsRpc/AddMessage"
	NewsRpc_UpdateMessage_FullMethodName          = "/newsrpc.NewsRpc/UpdateMessage"
	NewsRpc_GetMessage_FullMethodName             = "/newsrpc.NewsRpc/GetMessage"
	NewsRpc_DeletesMessage_FullMethodName         = "/newsrpc.NewsRpc/DeletesMessage"
	NewsRpc_FindMessageList_FullMethodName        = "/newsrpc.NewsRpc/FindMessageList"
	NewsRpc_UpdateMessageStatus_FullMethodName    = "/newsrpc.NewsRpc/UpdateMessageStatus"
	NewsRpc_AddComment_FullMethodName             = "/newsrpc.NewsRpc/AddComment"
	NewsRpc_UpdateComment_FullMethodName          = "/newsrpc.NewsRpc/UpdateComment"
	NewsRpc_GetComment_FullMethodName             = "/newsrpc.NewsRpc/GetComment"
	NewsRpc_DeletesComment_FullMethodName         = "/newsrpc.NewsRpc/DeletesComment"
	NewsRpc_FindCommentList_FullMethodName        = "/newsrpc.NewsRpc/FindCommentList"
	NewsRpc_FindCommentReplyList_FullMethodName   = "/newsrpc.NewsRpc/FindCommentReplyList"
	NewsRpc_FindCommentReplyCounts_FullMethodName = "/newsrpc.NewsRpc/FindCommentReplyCounts"
	NewsRpc_UpdateCommentStatus_FullMethodName    = "/newsrpc.NewsRpc/UpdateCommentStatus"
	NewsRpc_LikeComment_FullMethodName            = "/newsrpc.NewsRpc/LikeComment"
	NewsRpc_FindUserLikeComment_FullMethodName    = "/newsrpc.NewsRpc/FindUserLikeComment"
)

// NewsRpcClient is the client API for NewsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsRpcClient interface {
	// 消息数据分析
	AnalysisMessage(ctx context.Context, in *AnalysisMessageReq, opts ...grpc.CallOption) (*AnalysisMessageResp, error)
	// 创建聊天记录
	AddChat(ctx context.Context, in *AddChatReq, opts ...grpc.CallOption) (*AddChatResp, error)
	// 更新聊天记录
	UpdateChat(ctx context.Context, in *UpdateChatReq, opts ...grpc.CallOption) (*UpdateChatResp, error)
	// 查询聊天记录
	GetChat(ctx context.Context, in *GetChatReq, opts ...grpc.CallOption) (*GetChatResp, error)
	// 删除聊天记录
	DeletesChat(ctx context.Context, in *DeletesChatReq, opts ...grpc.CallOption) (*DeletesChatResp, error)
	// 查询聊天记录列表
	FindChatList(ctx context.Context, in *FindChatListReq, opts ...grpc.CallOption) (*FindChatListResp, error)
	// 创建留言
	AddMessage(ctx context.Context, in *AddMessageReq, opts ...grpc.CallOption) (*AddMessageResp, error)
	// 更新留言
	UpdateMessage(ctx context.Context, in *UpdateMessageReq, opts ...grpc.CallOption) (*UpdateMessageResp, error)
	// 查询留言
	GetMessage(ctx context.Context, in *GetMessageReq, opts ...grpc.CallOption) (*GetMessageResp, error)
	// 删除留言
	DeletesMessage(ctx context.Context, in *DeletesMessageReq, opts ...grpc.CallOption) (*DeletesMessageResp, error)
	// 查询留言列表
	FindMessageList(ctx context.Context, in *FindMessageListReq, opts ...grpc.CallOption) (*FindMessageListResp, error)
	// 更新留言状态
	UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusReq, opts ...grpc.CallOption) (*UpdateMessageStatusResp, error)
	// 创建评论
	AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*AddCommentResp, error)
	// 更新评论
	UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*UpdateCommentResp, error)
	// 查询评论
	GetComment(ctx context.Context, in *GetCommentReq, opts ...grpc.CallOption) (*GetCommentResp, error)
	// 删除评论
	DeletesComment(ctx context.Context, in *DeletesCommentReq, opts ...grpc.CallOption) (*DeletesCommentResp, error)
	// 查询评论列表
	FindCommentList(ctx context.Context, in *FindCommentListReq, opts ...grpc.CallOption) (*FindCommentListResp, error)
	// 查询评论回复列表
	FindCommentReplyList(ctx context.Context, in *FindCommentReplyListReq, opts ...grpc.CallOption) (*FindCommentReplyListResp, error)
	// 查询评论回复数量
	FindCommentReplyCounts(ctx context.Context, in *FindCommentReplyCountsReq, opts ...grpc.CallOption) (*FindCommentReplyCountsResp, error)
	// 更新评论状态
	UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*UpdateCommentStatusResp, error)
	// 点赞评论
	LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error)
	// 用户点赞的评论
	FindUserLikeComment(ctx context.Context, in *FindUserLikeCommentReq, opts ...grpc.CallOption) (*FindLikeCommentResp, error)
}

type newsRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsRpcClient(cc grpc.ClientConnInterface) NewsRpcClient {
	return &newsRpcClient{cc}
}

func (c *newsRpcClient) AnalysisMessage(ctx context.Context, in *AnalysisMessageReq, opts ...grpc.CallOption) (*AnalysisMessageResp, error) {
	out := new(AnalysisMessageResp)
	err := c.cc.Invoke(ctx, NewsRpc_AnalysisMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) AddChat(ctx context.Context, in *AddChatReq, opts ...grpc.CallOption) (*AddChatResp, error) {
	out := new(AddChatResp)
	err := c.cc.Invoke(ctx, NewsRpc_AddChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) UpdateChat(ctx context.Context, in *UpdateChatReq, opts ...grpc.CallOption) (*UpdateChatResp, error) {
	out := new(UpdateChatResp)
	err := c.cc.Invoke(ctx, NewsRpc_UpdateChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) GetChat(ctx context.Context, in *GetChatReq, opts ...grpc.CallOption) (*GetChatResp, error) {
	out := new(GetChatResp)
	err := c.cc.Invoke(ctx, NewsRpc_GetChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) DeletesChat(ctx context.Context, in *DeletesChatReq, opts ...grpc.CallOption) (*DeletesChatResp, error) {
	out := new(DeletesChatResp)
	err := c.cc.Invoke(ctx, NewsRpc_DeletesChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindChatList(ctx context.Context, in *FindChatListReq, opts ...grpc.CallOption) (*FindChatListResp, error) {
	out := new(FindChatListResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindChatList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) AddMessage(ctx context.Context, in *AddMessageReq, opts ...grpc.CallOption) (*AddMessageResp, error) {
	out := new(AddMessageResp)
	err := c.cc.Invoke(ctx, NewsRpc_AddMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) UpdateMessage(ctx context.Context, in *UpdateMessageReq, opts ...grpc.CallOption) (*UpdateMessageResp, error) {
	out := new(UpdateMessageResp)
	err := c.cc.Invoke(ctx, NewsRpc_UpdateMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) GetMessage(ctx context.Context, in *GetMessageReq, opts ...grpc.CallOption) (*GetMessageResp, error) {
	out := new(GetMessageResp)
	err := c.cc.Invoke(ctx, NewsRpc_GetMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) DeletesMessage(ctx context.Context, in *DeletesMessageReq, opts ...grpc.CallOption) (*DeletesMessageResp, error) {
	out := new(DeletesMessageResp)
	err := c.cc.Invoke(ctx, NewsRpc_DeletesMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindMessageList(ctx context.Context, in *FindMessageListReq, opts ...grpc.CallOption) (*FindMessageListResp, error) {
	out := new(FindMessageListResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindMessageList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusReq, opts ...grpc.CallOption) (*UpdateMessageStatusResp, error) {
	out := new(UpdateMessageStatusResp)
	err := c.cc.Invoke(ctx, NewsRpc_UpdateMessageStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*AddCommentResp, error) {
	out := new(AddCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_AddComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*UpdateCommentResp, error) {
	out := new(UpdateCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_UpdateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) GetComment(ctx context.Context, in *GetCommentReq, opts ...grpc.CallOption) (*GetCommentResp, error) {
	out := new(GetCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_GetComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) DeletesComment(ctx context.Context, in *DeletesCommentReq, opts ...grpc.CallOption) (*DeletesCommentResp, error) {
	out := new(DeletesCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_DeletesComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindCommentList(ctx context.Context, in *FindCommentListReq, opts ...grpc.CallOption) (*FindCommentListResp, error) {
	out := new(FindCommentListResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindCommentList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindCommentReplyList(ctx context.Context, in *FindCommentReplyListReq, opts ...grpc.CallOption) (*FindCommentReplyListResp, error) {
	out := new(FindCommentReplyListResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindCommentReplyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindCommentReplyCounts(ctx context.Context, in *FindCommentReplyCountsReq, opts ...grpc.CallOption) (*FindCommentReplyCountsResp, error) {
	out := new(FindCommentReplyCountsResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindCommentReplyCounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*UpdateCommentStatusResp, error) {
	out := new(UpdateCommentStatusResp)
	err := c.cc.Invoke(ctx, NewsRpc_UpdateCommentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error) {
	out := new(LikeCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_LikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsRpcClient) FindUserLikeComment(ctx context.Context, in *FindUserLikeCommentReq, opts ...grpc.CallOption) (*FindLikeCommentResp, error) {
	out := new(FindLikeCommentResp)
	err := c.cc.Invoke(ctx, NewsRpc_FindUserLikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsRpcServer is the server API for NewsRpc service.
// All implementations must embed UnimplementedNewsRpcServer
// for forward compatibility
type NewsRpcServer interface {
	// 消息数据分析
	AnalysisMessage(context.Context, *AnalysisMessageReq) (*AnalysisMessageResp, error)
	// 创建聊天记录
	AddChat(context.Context, *AddChatReq) (*AddChatResp, error)
	// 更新聊天记录
	UpdateChat(context.Context, *UpdateChatReq) (*UpdateChatResp, error)
	// 查询聊天记录
	GetChat(context.Context, *GetChatReq) (*GetChatResp, error)
	// 删除聊天记录
	DeletesChat(context.Context, *DeletesChatReq) (*DeletesChatResp, error)
	// 查询聊天记录列表
	FindChatList(context.Context, *FindChatListReq) (*FindChatListResp, error)
	// 创建留言
	AddMessage(context.Context, *AddMessageReq) (*AddMessageResp, error)
	// 更新留言
	UpdateMessage(context.Context, *UpdateMessageReq) (*UpdateMessageResp, error)
	// 查询留言
	GetMessage(context.Context, *GetMessageReq) (*GetMessageResp, error)
	// 删除留言
	DeletesMessage(context.Context, *DeletesMessageReq) (*DeletesMessageResp, error)
	// 查询留言列表
	FindMessageList(context.Context, *FindMessageListReq) (*FindMessageListResp, error)
	// 更新留言状态
	UpdateMessageStatus(context.Context, *UpdateMessageStatusReq) (*UpdateMessageStatusResp, error)
	// 创建评论
	AddComment(context.Context, *AddCommentReq) (*AddCommentResp, error)
	// 更新评论
	UpdateComment(context.Context, *UpdateCommentReq) (*UpdateCommentResp, error)
	// 查询评论
	GetComment(context.Context, *GetCommentReq) (*GetCommentResp, error)
	// 删除评论
	DeletesComment(context.Context, *DeletesCommentReq) (*DeletesCommentResp, error)
	// 查询评论列表
	FindCommentList(context.Context, *FindCommentListReq) (*FindCommentListResp, error)
	// 查询评论回复列表
	FindCommentReplyList(context.Context, *FindCommentReplyListReq) (*FindCommentReplyListResp, error)
	// 查询评论回复数量
	FindCommentReplyCounts(context.Context, *FindCommentReplyCountsReq) (*FindCommentReplyCountsResp, error)
	// 更新评论状态
	UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*UpdateCommentStatusResp, error)
	// 点赞评论
	LikeComment(context.Context, *LikeCommentReq) (*LikeCommentResp, error)
	// 用户点赞的评论
	FindUserLikeComment(context.Context, *FindUserLikeCommentReq) (*FindLikeCommentResp, error)
	mustEmbedUnimplementedNewsRpcServer()
}

// UnimplementedNewsRpcServer must be embedded to have forward compatible implementations.
type UnimplementedNewsRpcServer struct {
}

func (UnimplementedNewsRpcServer) AnalysisMessage(context.Context, *AnalysisMessageReq) (*AnalysisMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalysisMessage not implemented")
}
func (UnimplementedNewsRpcServer) AddChat(context.Context, *AddChatReq) (*AddChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChat not implemented")
}
func (UnimplementedNewsRpcServer) UpdateChat(context.Context, *UpdateChatReq) (*UpdateChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChat not implemented")
}
func (UnimplementedNewsRpcServer) GetChat(context.Context, *GetChatReq) (*GetChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedNewsRpcServer) DeletesChat(context.Context, *DeletesChatReq) (*DeletesChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesChat not implemented")
}
func (UnimplementedNewsRpcServer) FindChatList(context.Context, *FindChatListReq) (*FindChatListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindChatList not implemented")
}
func (UnimplementedNewsRpcServer) AddMessage(context.Context, *AddMessageReq) (*AddMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedNewsRpcServer) UpdateMessage(context.Context, *UpdateMessageReq) (*UpdateMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (UnimplementedNewsRpcServer) GetMessage(context.Context, *GetMessageReq) (*GetMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedNewsRpcServer) DeletesMessage(context.Context, *DeletesMessageReq) (*DeletesMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesMessage not implemented")
}
func (UnimplementedNewsRpcServer) FindMessageList(context.Context, *FindMessageListReq) (*FindMessageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMessageList not implemented")
}
func (UnimplementedNewsRpcServer) UpdateMessageStatus(context.Context, *UpdateMessageStatusReq) (*UpdateMessageStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessageStatus not implemented")
}
func (UnimplementedNewsRpcServer) AddComment(context.Context, *AddCommentReq) (*AddCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedNewsRpcServer) UpdateComment(context.Context, *UpdateCommentReq) (*UpdateCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedNewsRpcServer) GetComment(context.Context, *GetCommentReq) (*GetCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedNewsRpcServer) DeletesComment(context.Context, *DeletesCommentReq) (*DeletesCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletesComment not implemented")
}
func (UnimplementedNewsRpcServer) FindCommentList(context.Context, *FindCommentListReq) (*FindCommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentList not implemented")
}
func (UnimplementedNewsRpcServer) FindCommentReplyList(context.Context, *FindCommentReplyListReq) (*FindCommentReplyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentReplyList not implemented")
}
func (UnimplementedNewsRpcServer) FindCommentReplyCounts(context.Context, *FindCommentReplyCountsReq) (*FindCommentReplyCountsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommentReplyCounts not implemented")
}
func (UnimplementedNewsRpcServer) UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*UpdateCommentStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommentStatus not implemented")
}
func (UnimplementedNewsRpcServer) LikeComment(context.Context, *LikeCommentReq) (*LikeCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedNewsRpcServer) FindUserLikeComment(context.Context, *FindUserLikeCommentReq) (*FindLikeCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserLikeComment not implemented")
}
func (UnimplementedNewsRpcServer) mustEmbedUnimplementedNewsRpcServer() {}

// UnsafeNewsRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsRpcServer will
// result in compilation errors.
type UnsafeNewsRpcServer interface {
	mustEmbedUnimplementedNewsRpcServer()
}

func RegisterNewsRpcServer(s grpc.ServiceRegistrar, srv NewsRpcServer) {
	s.RegisterService(&NewsRpc_ServiceDesc, srv)
}

func _NewsRpc_AnalysisMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).AnalysisMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_AnalysisMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).AnalysisMessage(ctx, req.(*AnalysisMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_AddChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).AddChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_AddChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).AddChat(ctx, req.(*AddChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_UpdateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).UpdateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_UpdateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).UpdateChat(ctx, req.(*UpdateChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).GetChat(ctx, req.(*GetChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_DeletesChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).DeletesChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_DeletesChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).DeletesChat(ctx, req.(*DeletesChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindChatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindChatList(ctx, req.(*FindChatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).AddMessage(ctx, req.(*AddMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_UpdateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).UpdateMessage(ctx, req.(*UpdateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).GetMessage(ctx, req.(*GetMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_DeletesMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).DeletesMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_DeletesMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).DeletesMessage(ctx, req.(*DeletesMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindMessageList(ctx, req.(*FindMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_UpdateMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).UpdateMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_UpdateMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).UpdateMessageStatus(ctx, req.(*UpdateMessageStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).AddComment(ctx, req.(*AddCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).UpdateComment(ctx, req.(*UpdateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).GetComment(ctx, req.(*GetCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_DeletesComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).DeletesComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_DeletesComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).DeletesComment(ctx, req.(*DeletesCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindCommentList(ctx, req.(*FindCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindCommentReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentReplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindCommentReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindCommentReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindCommentReplyList(ctx, req.(*FindCommentReplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindCommentReplyCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommentReplyCountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindCommentReplyCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindCommentReplyCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindCommentReplyCounts(ctx, req.(*FindCommentReplyCountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_UpdateCommentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).UpdateCommentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_UpdateCommentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).UpdateCommentStatus(ctx, req.(*UpdateCommentStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).LikeComment(ctx, req.(*LikeCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsRpc_FindUserLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserLikeCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsRpcServer).FindUserLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsRpc_FindUserLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsRpcServer).FindUserLikeComment(ctx, req.(*FindUserLikeCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsRpc_ServiceDesc is the grpc.ServiceDesc for NewsRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newsrpc.NewsRpc",
	HandlerType: (*NewsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalysisMessage",
			Handler:    _NewsRpc_AnalysisMessage_Handler,
		},
		{
			MethodName: "AddChat",
			Handler:    _NewsRpc_AddChat_Handler,
		},
		{
			MethodName: "UpdateChat",
			Handler:    _NewsRpc_UpdateChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _NewsRpc_GetChat_Handler,
		},
		{
			MethodName: "DeletesChat",
			Handler:    _NewsRpc_DeletesChat_Handler,
		},
		{
			MethodName: "FindChatList",
			Handler:    _NewsRpc_FindChatList_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _NewsRpc_AddMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _NewsRpc_UpdateMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _NewsRpc_GetMessage_Handler,
		},
		{
			MethodName: "DeletesMessage",
			Handler:    _NewsRpc_DeletesMessage_Handler,
		},
		{
			MethodName: "FindMessageList",
			Handler:    _NewsRpc_FindMessageList_Handler,
		},
		{
			MethodName: "UpdateMessageStatus",
			Handler:    _NewsRpc_UpdateMessageStatus_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _NewsRpc_AddComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _NewsRpc_UpdateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _NewsRpc_GetComment_Handler,
		},
		{
			MethodName: "DeletesComment",
			Handler:    _NewsRpc_DeletesComment_Handler,
		},
		{
			MethodName: "FindCommentList",
			Handler:    _NewsRpc_FindCommentList_Handler,
		},
		{
			MethodName: "FindCommentReplyList",
			Handler:    _NewsRpc_FindCommentReplyList_Handler,
		},
		{
			MethodName: "FindCommentReplyCounts",
			Handler:    _NewsRpc_FindCommentReplyCounts_Handler,
		},
		{
			MethodName: "UpdateCommentStatus",
			Handler:    _NewsRpc_UpdateCommentStatus_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _NewsRpc_LikeComment_Handler,
		},
		{
			MethodName: "FindUserLikeComment",
			Handler:    _NewsRpc_FindUserLikeComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news.proto",
}
