version: "3"

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:
  ve-blog-vite:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ve-blog-vite:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-vite
    restart: always
    ports:
      - "8888:80"
