version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker


      # 查看初始化登录密码 user:veweiyi pwd:veweiyi
      # cat /home/docker/jenkins/secrets/initialAdminPassword
      # 查看用户密码 /home/docker/jenkins/users
