// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package menurpc

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/server/zero/rpc/pb/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Api           = blog.Api
	Article       = blog.Article
	BatchResult   = blog.BatchResult
	EmptyReq      = blog.EmptyReq
	EmptyResp     = blog.EmptyResp
	IdReq         = blog.IdReq
	IdsReq        = blog.IdsReq
	Menu          = blog.Menu
	PageCondition = blog.PageCondition
	PageLimit     = blog.PageLimit
	PageQuery     = blog.PageQuery
	PageResult    = blog.PageResult
	PageSort      = blog.PageSort
	PingReq       = blog.PingReq
	PingResp      = blog.PingResp
	Role          = blog.Role

	MenuRpc interface {
		CreateMenu(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error)
		UpdateMenu(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error)
		DeleteMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		FindMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error)
		DeleteMenuList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResult, error)
		FindMenuList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	}

	defaultMenuRpc struct {
		cli zrpc.Client
	}
)

func NewMenuRpc(cli zrpc.Client) MenuRpc {
	return &defaultMenuRpc{
		cli: cli,
	}
}

func (m *defaultMenuRpc) CreateMenu(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultMenuRpc) UpdateMenu(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultMenuRpc) DeleteMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultMenuRpc) FindMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.FindMenu(ctx, in, opts...)
}

func (m *defaultMenuRpc) DeleteMenuList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResult, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.DeleteMenuList(ctx, in, opts...)
}

func (m *defaultMenuRpc) FindMenuList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	client := blog.NewMenuRpcClient(m.cli.Conn())
	return client.FindMenuList(ctx, in, opts...)
}
