// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package logrpc

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/rpc/blog/internal/pb/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalysisArticleResp       = blog.AnalysisArticleResp
	Api                       = blog.Api
	ApiDetails                = blog.ApiDetails
	ArticleCategory           = blog.ArticleCategory
	ArticleDetails            = blog.ArticleDetails
	ArticleNew                = blog.ArticleNew
	ArticleTag                = blog.ArticleTag
	BatchResp                 = blog.BatchResp
	BindUserEmailReq          = blog.BindUserEmailReq
	CategoryDetails           = blog.CategoryDetails
	CategoryNew               = blog.CategoryNew
	ChatRecord                = blog.ChatRecord
	Comment                   = blog.Comment
	CommentUserInfo           = blog.CommentUserInfo
	CountResp                 = blog.CountResp
	EmptyReq                  = blog.EmptyReq
	EmptyResp                 = blog.EmptyResp
	FindApiListResp           = blog.FindApiListResp
	FindArticleListReq        = blog.FindArticleListReq
	FindArticleListResp       = blog.FindArticleListResp
	FindArticlesByCategoryReq = blog.FindArticlesByCategoryReq
	FindArticlesByTagReq      = blog.FindArticlesByTagReq
	FindCategoryListReq       = blog.FindCategoryListReq
	FindCategoryListResp      = blog.FindCategoryListResp
	FindChatRecordListResp    = blog.FindChatRecordListResp
	FindCommentListResp       = blog.FindCommentListResp
	FindConfigReq             = blog.FindConfigReq
	FindConfigResp            = blog.FindConfigResp
	FindFriendLinkListResp    = blog.FindFriendLinkListResp
	FindLikeArticleResp       = blog.FindLikeArticleResp
	FindLikeCommentResp       = blog.FindLikeCommentResp
	FindLikeTalkResp          = blog.FindLikeTalkResp
	FindLoginHistoryListReq   = blog.FindLoginHistoryListReq
	FindLoginHistoryListResp  = blog.FindLoginHistoryListResp
	FindMenuListResp          = blog.FindMenuListResp
	FindOperationLogListResp  = blog.FindOperationLogListResp
	FindPageListResp          = blog.FindPageListResp
	FindPhotoAlbumListResp    = blog.FindPhotoAlbumListResp
	FindPhotoListResp         = blog.FindPhotoListResp
	FindRemarkListResp        = blog.FindRemarkListResp
	FindRoleListResp          = blog.FindRoleListResp
	FindTagArticleCountReq    = blog.FindTagArticleCountReq
	FindTagByNameReq          = blog.FindTagByNameReq
	FindTagListReq            = blog.FindTagListReq
	FindTagListResp           = blog.FindTagListResp
	FindTalkListResp          = blog.FindTalkListResp
	FindUserListReq           = blog.FindUserListReq
	FindUserListResp          = blog.FindUserListResp
	FindUserRegionListResp    = blog.FindUserRegionListResp
	FriendLink                = blog.FriendLink
	GetLogoutAtReq            = blog.GetLogoutAtReq
	IdReq                     = blog.IdReq
	IdsReq                    = blog.IdsReq
	ListResp                  = blog.ListResp
	LoginReq                  = blog.LoginReq
	LoginResp                 = blog.LoginResp
	LogoffReq                 = blog.LogoffReq
	LogoutReq                 = blog.LogoutReq
	LogoutResp                = blog.LogoutResp
	Menu                      = blog.Menu
	MenuDetails               = blog.MenuDetails
	OauthLoginReq             = blog.OauthLoginReq
	OauthLoginUrlResp         = blog.OauthLoginUrlResp
	OperationLog              = blog.OperationLog
	Page                      = blog.Page
	PageCondition             = blog.PageCondition
	PageLimit                 = blog.PageLimit
	PageQuery                 = blog.PageQuery
	PageSort                  = blog.PageSort
	Photo                     = blog.Photo
	PhotoAlbum                = blog.PhotoAlbum
	RecycleArticleReq         = blog.RecycleArticleReq
	RegisterReq               = blog.RegisterReq
	Remark                    = blog.Remark
	ResetPasswordReq          = blog.ResetPasswordReq
	Role                      = blog.Role
	RoleDetails               = blog.RoleDetails
	RoleResourcesResp         = blog.RoleResourcesResp
	SaveConfigReq             = blog.SaveConfigReq
	SyncMenuReq               = blog.SyncMenuReq
	TagDetails                = blog.TagDetails
	TagMapResp                = blog.TagMapResp
	TagNew                    = blog.TagNew
	Talk                      = blog.Talk
	TalkDetailsDTO            = blog.TalkDetailsDTO
	TopArticleReq             = blog.TopArticleReq
	UpdateRoleApisReq         = blog.UpdateRoleApisReq
	UpdateRoleMenusReq        = blog.UpdateRoleMenusReq
	UpdateUserInfoReq         = blog.UpdateUserInfoReq
	UpdateUserRoleReq         = blog.UpdateUserRoleReq
	UpdateUserStatusReq       = blog.UpdateUserStatusReq
	UploadRecordReq           = blog.UploadRecordReq
	UploadRecordResp          = blog.UploadRecordResp
	UserDetails               = blog.UserDetails
	UserEmailReq              = blog.UserEmailReq
	UserIdReq                 = blog.UserIdReq
	UserInfoResp              = blog.UserInfoResp
	UserLoginHistory          = blog.UserLoginHistory
	UserRegion                = blog.UserRegion
	UserRoleLabel             = blog.UserRoleLabel
	UserVisit                 = blog.UserVisit
	UserVisitPageRsp          = blog.UserVisitPageRsp

	LogRpc interface {
		// 创建操作记录
		AddOperationLog(ctx context.Context, in *OperationLog, opts ...grpc.CallOption) (*OperationLog, error)
		// 更新操作记录
		UpdateOperationLog(ctx context.Context, in *OperationLog, opts ...grpc.CallOption) (*OperationLog, error)
		// 删除操作记录
		DeleteOperationLog(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 批量删除操作记录
		DeleteOperationLogList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error)
		// 查询操作记录
		FindOperationLog(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperationLog, error)
		// 查询操作记录列表
		FindOperationLogList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*FindOperationLogListResp, error)
		// 查询操作记录数量
		FindOperationLogCount(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*CountResp, error)
	}

	defaultLogRpc struct {
		cli zrpc.Client
	}
)

func NewLogRpc(cli zrpc.Client) LogRpc {
	return &defaultLogRpc{
		cli: cli,
	}
}

// 创建操作记录
func (m *defaultLogRpc) AddOperationLog(ctx context.Context, in *OperationLog, opts ...grpc.CallOption) (*OperationLog, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.AddOperationLog(ctx, in, opts...)
}

// 更新操作记录
func (m *defaultLogRpc) UpdateOperationLog(ctx context.Context, in *OperationLog, opts ...grpc.CallOption) (*OperationLog, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.UpdateOperationLog(ctx, in, opts...)
}

// 删除操作记录
func (m *defaultLogRpc) DeleteOperationLog(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.DeleteOperationLog(ctx, in, opts...)
}

// 批量删除操作记录
func (m *defaultLogRpc) DeleteOperationLogList(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*BatchResp, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.DeleteOperationLogList(ctx, in, opts...)
}

// 查询操作记录
func (m *defaultLogRpc) FindOperationLog(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperationLog, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.FindOperationLog(ctx, in, opts...)
}

// 查询操作记录列表
func (m *defaultLogRpc) FindOperationLogList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*FindOperationLogListResp, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.FindOperationLogList(ctx, in, opts...)
}

// 查询操作记录数量
func (m *defaultLogRpc) FindOperationLogCount(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*CountResp, error) {
	client := blog.NewLogRpcClient(m.cli.Conn())
	return client.FindOperationLogCount(ctx, in, opts...)
}
