// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BindUserEmailReq struct {
	Email      string `json:"email"`       // 邮箱
	VerifyCode string `json:"verify_code"` // 验证码
}

type BindUserPhoneReq struct {
	Mobile     string `json:"mobile"`      // 手机号
	VerifyCode string `json:"verify_code"` // 验证码
}

type BindUserThirdPartyReq struct {
	Platform string `json:"platform"`       // 平台
	Code     string `json:"code"`           // 授权码
	State    string `json:"state,optional"` // 状态
}

type GetUserApisResp struct {
	List []*UserApi `json:"list"`
}

type GetUserMenusResp struct {
	List []*UserMenu `json:"list"`
}

type GetUserProfileReq struct {
}

type GetUserRolesResp struct {
	List []*UserRole `json:"list"`
}

type QueryUserLoginHistoryReq struct {
	PageQuery
}

type UnbindUserThirdPartyReq struct {
	Platform string `json:"platform"` // 平台
}

type UpdateUserAvatarReq struct {
	Avatar string `json:"avatar"` // 头像
}

type UpdateUserPasswordReq struct {
	OldPassword     string `json:"old_password"`     // 旧密码
	NewPassword     string `json:"new_password"`     // 新密码
	ConfirmPassword string `json:"confirm_password"` // 确认密码
}

type UpdateUserProfileReq struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"` // 用户头像
	UserInfoExt
}

type UserProfile struct {
	UserId     string                `json:"user_id"`     // 用户ID（UUID）
	Username   string                `json:"username"`    // 用户名
	Nickname   string                `json:"nickname"`    // 真实姓名
	Avatar     string                `json:"avatar"`      // 头像
	Email      string                `json:"email"`       // 邮箱
	Mobile     string                `json:"mobile"`      // 手机号
	Status     int64                 `json:"status"`      // 状态：0-禁用 1-正常 2-冻结
	CreatedAt  int64                 `json:"created_at"`  // 创建时间（毫秒时间戳）
	UpdatedAt  int64                 `json:"updated_at"`  // 更新时间（毫秒时间戳）
	ThirdParty []*UserThirdPartyInfo `json:"third_party"` // 第三方绑定
	Roles      []string              `json:"roles"`
	Perms      []string              `json:"perms"`
	UserInfoExt
}
