// Code generated by goctl. DO NOT EDIT.
// Source: blog.proto

package server

import (
	"context"

	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/logic/menurpc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/internal/svc"
	"github.com/ve-weiyi/ve-blog-golang/zero/service/blog/rpc/pb/blog"
)

type MenuRpcServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedMenuRpcServer
}

func NewMenuRpcServer(svcCtx *svc.ServiceContext) *MenuRpcServer {
	return &MenuRpcServer{
		svcCtx: svcCtx,
	}
}

// 创建菜单
func (s *MenuRpcServer) CreateMenu(ctx context.Context, in *blog.Menu) (*blog.Menu, error) {
	l := menurpclogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

// 更新菜单
func (s *MenuRpcServer) UpdateMenu(ctx context.Context, in *blog.Menu) (*blog.Menu, error) {
	l := menurpclogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

// 删除菜单
func (s *MenuRpcServer) DeleteMenu(ctx context.Context, in *blog.IdReq) (*blog.BatchResp, error) {
	l := menurpclogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

// 批量删除菜单
func (s *MenuRpcServer) DeleteMenuList(ctx context.Context, in *blog.IdsReq) (*blog.BatchResp, error) {
	l := menurpclogic.NewDeleteMenuListLogic(ctx, s.svcCtx)
	return l.DeleteMenuList(in)
}

// 查询菜单
func (s *MenuRpcServer) FindMenu(ctx context.Context, in *blog.IdReq) (*blog.Menu, error) {
	l := menurpclogic.NewFindMenuLogic(ctx, s.svcCtx)
	return l.FindMenu(in)
}

// 分页获取菜单列表
func (s *MenuRpcServer) FindMenuList(ctx context.Context, in *blog.PageQuery) (*blog.MenuPageResp, error) {
	l := menurpclogic.NewFindMenuListLogic(ctx, s.svcCtx)
	return l.FindMenuList(in)
}

// 同步菜单列表
func (s *MenuRpcServer) SyncMenuList(ctx context.Context, in *blog.SyncMenuRequest) (*blog.BatchResp, error) {
	l := menurpclogic.NewSyncMenuListLogic(ctx, s.svcCtx)
	return l.SyncMenuList(in)
}

// 清空菜单列表
func (s *MenuRpcServer) CleanMenuList(ctx context.Context, in *blog.EmptyReq) (*blog.BatchResp, error) {
	l := menurpclogic.NewCleanMenuListLogic(ctx, s.svcCtx)
	return l.CleanMenuList(in)
}
