version: "3"

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:
  ve-blog-golang-rpc:
    build:
      context: ./
      dockerfile: Dockerfile-rpc
    image: ve-blog-golang-rpc:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-golang-rpc
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./runtime/rpc:/app/rpc/blog/runtime

  ve-blog-golang-blog-api:
    build:
      context: ./
      dockerfile: Dockerfile-blog-api
    image: ve-blog-golang-blog-api:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-golang-blog-api
    restart: always
    ports:
      - "6060:6060"
      - "9090:9090"
    volumes:
      - ./runtime/api:/app/api/blog/runtime
    depends_on:
      - ve-blog-golang-rpc

  ve-blog-golang-admin-api:
    build:
      context: ./
      dockerfile: Dockerfile-admin-api
    image: ve-blog-golang-admin-api:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-golang-admin-api
    restart: always
    ports:
      - "6061:6061"
      - "9091:9091"
    volumes:
      - ./runtime/api:/app/api/admin/runtime
    depends_on:
      - ve-blog-golang-rpc
#docker network create blog-network
#networks:
#  blog-network:
#    external: true
