FROM golang:alpine AS builder

WORKDIR /go/src/github.com/ve-weiyi/ve-blog-golang/zero
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy

COPY service/blog/api/etc /app/api/etc
RUN go build -ldflags="-s -w" -o /app/api/blog service/blog/api/blog.go

#FROM alpine:latest
#
#维护者信息
LABEL maintainer="791422171@qq.com"
#
WORKDIR /app/api
#COPY --from=0 /app/blog /app/blog
#COPY --from=0 /app/etc /app/etc
#
EXPOSE 9999
EXPOSE 6060

# 启动命令，只能有一个生效
ENTRYPOINT ./blog
