FROM golang:alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# 安装必要的依赖
RUN apk update --no-cache
RUN apk add --no-cache git
RUN apk add --no-cache tzdata

WORKDIR /

# 下载项目
RUN git init
RUN git clone https://github.com/ve-weiyi/ve-blog-golang.git

# 切换到项目目录
WORKDIR /ve-blog-golang/zero

# 切换到目标分支并拉取最新代码
RUN git checkout feature/v1.0.0/go-zero
RUN go mod tidy

COPY service/blog/rpc/etc /app/rpc/etc
RUN go build -ldflags="-s -w" -o /app/rpc/blog service/blog/rpc/blog.go

#维护者信息
LABEL maintainer="791422171@qq.com"

ENV TZ Asia/Shanghai
WORKDIR /app/rpc

# 暴露应用程序的端口
EXPOSE 9998

# 启动命令，只能有一个生效
ENTRYPOINT ./blog
