// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type TagBackVO struct {
	Id           int64  `json:"id,optional"`   // 标签ID
	TagName      string `json:"tag_name"`      // 标签名
	ArticleCount int64  `json:"article_count"` // 文章数量
	CreatedAt    int64  `json:"created_at"`    // 创建时间
	UpdatedAt    int64  `json:"updated_at"`    // 更新时间
}

type TagNewReq struct {
	Id      int64  `json:"id,optional"`
	TagName string `json:"tag_name"` // 标签名
}

type TagQuery struct {
	PageQuery
	TagName string `json:"tag_name,optional"` // 标签名
}
