version: "3"

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:

  blog-rpc:
    build:
      context: ./
      dockerfile: Dockerfile-rpc
    image: blog-rpc:latest  # 设置新的镜像名称和标签
    container_name: blog-rpc
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./runtime/rpc:/app/rpc/blog/runtime

  blog-api:
    build:
      context: ./
      dockerfile: Dockerfile-blog-api
    image: blog-api:latest  # 设置新的镜像名称和标签
    container_name: blog-api
    restart: always
    ports:
      - "6060:6060"
      - "9090:9090"
    volumes:
      - ./runtime/api:/app/api/blog/runtime
    depends_on:
      - blog-rpc

  admin-api:
    build:
      context: ./
      dockerfile: Dockerfile-admin-api
    image: admin-api:latest  # 设置新的镜像名称和标签
    container_name: admin-api
    restart: always
    ports:
      - "6061:6061"
      - "9091:9091"
    volumes:
      - ./runtime/api:/app/api/admin/runtime
    depends_on:
      - blog-rpc
#docker network create blog-network
#networks:
#  blog-network:
#    external: true
