version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/jenkins:/var/jenkins_home
      - # 查看初始化登录密码
      # cat /home/docker/jenkins/secrets/initialAdminPassword
