version: "3"

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:
  ve-blog:
    build:
      context: ../docker
      dockerfile: Dockerfile
    image: ve-blog:latest  # 设置新的镜像名称和标签
    container_name: ve-blog-server
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /home/docker/blog:/home/docker/blog
