version: "3"

services:
  ve-blog:
    build:
      context: ../docker
      dockerfile: Dockerfile
    image: ve-blog:latest  # 设置新的镜像名称和标签
    restart: always
    container_name: ve-blog-server
    ports:
      - "9999:9999"
    volumes:
      - /home/blog:/home/blog
