version: "3"
services:
  redis:
    image: redis
    container_name: redis-server # 容器名
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /home/redis:/data
    environment:
      - REDIS_PASSWORD=redis7914 # redis只有密码，没有账号设置
