# compose版本，向下兼容，我选的最高版本
version: '3.9'

# 定义全局变量
x-common-variables: &common-variables
  volume_dir: /home/docker

# 定义服务
services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone  # 单机模式mysql
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: nacos-mysql
      MYSQL_SERVICE_PORT: 3307
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=100000&socketTimeout=300000&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      NACOS_AUTH_IDENTITY_KEY: 2222
      NACOS_AUTH_IDENTITY_VALUE: 2xxx
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_ENABLE: true  #开启鉴权
    depends_on:
      nacos-mysql:
        condition: service_healthy

    links:
      - nacos-mysql:nacos-mysql
    volumes:
      # 具名挂载数据卷，后面为对应容器内部地址，具名挂载数据卷，后面为对应容器内部地址
      # 生成的本机目录格式：/var/lib/docker/volumes/当前docker-compose.yml所在文件夹名称(根目录的话为default)_卷名/_data
      # 日志挂载
      - /home/docker/nacos/log:/home/nacos/logs
      # 配置挂载
      - /home/docker/nacos/conf:/home/nacos/conf

  nacos-mysql:
    image: mysql:8.0.34
    container_name: nacos-mysql
    ports:
      - "3307:3306"
    # 重启策略
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: "123456"
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: nacos_config
      # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
      MYSQL_USER: nacos
      # 用户密码
      MYSQL_PASSWORD: nacos
      # 映射端口
    volumes:
      # 数据挂载          data 文件夹是数据存储目录  (如果mysql初始化错误  需要将文件夹内部全部删除)
      - /home/docker/nacos_mysql/data:/var/lib/mysql/
      # 配置挂载          conf 文件夹 放置 my.cnf 配置文件
      - /home/docker/nacos_mysql/conf:/etc/mysql/conf.d/
      # 初始化目录挂载    init 文件夹可以放置 .sh .sql 文件 在初始化容器时会执行
      # nacos为当前堆栈(stack)的命名：/var/lib/docker/volumes/nacos_mysql_init/_data
      - /home/docker/nacos_mysql/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
# 其他配置 网络/卷、全局规则
volumes:
  # 如果有xxx_data这个卷就会直接使用它，否则会创建一个新的卷并使用
  nacos_log: { }
  nacos_conf: { }
  mysql_data: { }
  mysql_conf: { }
  mysql_init: { }
