name: Cleanup Old Packages
on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00 UTC 运行
  workflow_dispatch:      # 支持手动触发
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 必须要有 packages 的写入权限
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v1
        with:
          # 要清理的 Package 名称（支持通配符 *）
          package-name: 'feature*'
          # 保留最新的 N 个版本
          keep-latest: 5
          # 可选：删除早于 X 天的版本
          older-than-days: 30
